-- Phase 0 — Supercycle catalogue moves from hardcoded frontend into Postgres.
--
-- Source of truth for this seed: apps/frontend/src/lib/supercycleData.ts
-- (SUPERCYCLE_ARCHETYPES + SUPERCYCLE_SLOT_COLORS). The tuples below are
-- GENERATED from that module (scratchpad/gen-template-seed.mts), so the DB
-- template is byte-for-byte identical to what the UI renders today. This is a
-- purely additive migration: nothing reads this table yet. Later phases seed a
-- company's editable skeleton (pms_sc_nodes/subnodes/stages) FROM these rows.
--
-- `nodes` is the full per-archetype tree so the whole catalogue for one
-- business model is one row:
--   [{ id, label, color, slot, subNodes:[{id,label}],
--      subCycle:{ id, label, stages:[...] } }, ... ]  (exactly 5 nodes)

CREATE TABLE public.pms_archetype_templates (
  archetype_id  text PRIMARY KEY
    CHECK (archetype_id IN ('b2b_saas','deep_tech','d2c','manufacturing','consulting','education')),
  label         text NOT NULL,
  revenue_model text NOT NULL,
  slot_colors   text[] NOT NULL,          -- 5 ring-slot hues, index 0-4
  optional_nodes text[] NOT NULL DEFAULT '{}',
  nodes         jsonb NOT NULL,           -- the archetype's node/sub-node/stage tree
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER pms_archetype_templates_updated_at BEFORE UPDATE ON public.pms_archetype_templates
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Backend-only (service role). This catalogue is global, not company-scoped;
-- the browser never reads it directly, so deny anon/authenticated.
REVOKE ALL PRIVILEGES ON TABLE public.pms_archetype_templates FROM anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE public.pms_archetype_templates TO service_role;

INSERT INTO public.pms_archetype_templates
  (archetype_id, label, revenue_model, slot_colors, optional_nodes, nodes)
VALUES
  ('b2b_saas', 'B2B SaaS', 'Subscriptions, enterprise contracts and recurring renewals', ARRAY['#4fa8ff','#a855f7','#22c55e','#f0a83f','#2dd4bf']::text[], ARRAY['Partnerships']::text[], '[{"id":"product","label":"Product","color":"#4fa8ff","slot":0,"subNodes":[{"id":"product_core_product","label":"Core product"},{"id":"product_growth_features","label":"Growth features"}],"subCycle":{"id":"product_cycle","label":"Feature-led growth","stages":["Feedback","Prioritise","Build","Release","Measure"]}},{"id":"marketing","label":"Marketing","color":"#a855f7","slot":1,"subNodes":[{"id":"marketing_abm","label":"ABM"},{"id":"marketing_performance","label":"Performance"},{"id":"marketing_content","label":"Content"}],"subCycle":{"id":"marketing_cycle","label":"Demand generation","stages":["Segment","Campaign","Engage","Capture","Nurture"]}},{"id":"sales","label":"Sales","color":"#22c55e","slot":2,"subNodes":[{"id":"sales_enterprise","label":"Enterprise"},{"id":"sales_smb","label":"SMB"},{"id":"sales_channel","label":"Channel"}],"subCycle":{"id":"sales_cycle","label":"Enterprise sales","stages":["Qualify","Discovery","Demo","Proposal","Negotiate","Close"]}},{"id":"finance","label":"Finance","color":"#f0a83f","slot":3,"subNodes":[{"id":"finance_pricing","label":"Pricing"},{"id":"finance_billing","label":"Billing"},{"id":"finance_collections","label":"Collections"}],"subCycle":{"id":"finance_cycle","label":"Subscription billing","stages":["Price","Contract","Invoice","Collect","Recognise"]}},{"id":"success","label":"Customer Success","color":"#2dd4bf","slot":4,"subNodes":[{"id":"success_onboarding","label":"Onboarding"},{"id":"success_adoption","label":"Adoption"},{"id":"success_renewal","label":"Renewal"}],"subCycle":{"id":"success_cycle","label":"High-touch SaaS success","stages":["Onboard","Adopt","Monitor","Support","Renew","Expand"]}}]'::jsonb),
  ('deep_tech', 'Deep-Tech / Government', 'Institutional sales, tenders, milestone payments, long implementation cycles', ARRAY['#4fa8ff','#a855f7','#22c55e','#f0a83f','#2dd4bf']::text[], ARRAY['Partnerships','Government Relations','Legal']::text[], '[{"id":"solution","label":"Solution","color":"#4fa8ff","slot":0,"subNodes":[{"id":"solution_solution_design","label":"Solution design"},{"id":"solution_technical_presales","label":"Technical presales"}],"subCycle":{"id":"solution_cycle","label":"Solution engineering","stages":["Need","Design","Pilot","Validate","Customise"]}},{"id":"inst_marketing","label":"Institutional Mktg","color":"#a855f7","slot":1,"subNodes":[{"id":"inst_marketing_thought_leadership","label":"Thought leadership"},{"id":"inst_marketing_events","label":"Events"},{"id":"inst_marketing_outreach","label":"Outreach"}],"subCycle":{"id":"inst_marketing_cycle","label":"Institutional demand","stages":["Target","Educate","Demonstrate","Engage","Qualify"]}},{"id":"sales","label":"Sales","color":"#22c55e","slot":2,"subNodes":[{"id":"sales_government","label":"Government"},{"id":"sales_institutional","label":"Institutional"},{"id":"sales_consultant_led","label":"Consultant-led"}],"subCycle":{"id":"sales_cycle","label":"Tender / consultative sales","stages":["Opportunity","Eligibility","Technical","Bid","Commercial","Award"]}},{"id":"finance","label":"Finance","color":"#f0a83f","slot":3,"subNodes":[{"id":"finance_advance","label":"Advance"},{"id":"finance_milestone_billing","label":"Milestone billing"},{"id":"finance_grants","label":"Grants"}],"subCycle":{"id":"finance_cycle","label":"Milestone finance","stages":["Budget","Advance","Milestone","Certification","Invoice","Collection"]}},{"id":"implementation","label":"Implementation","color":"#2dd4bf","slot":4,"subNodes":[{"id":"implementation_deployment","label":"Deployment"},{"id":"implementation_training","label":"Training"},{"id":"implementation_acceptance","label":"Acceptance"}],"subCycle":{"id":"implementation_cycle","label":"Implementation success","stages":["Kickoff","Deploy","Train","Accept","Support","Extend"]}}]'::jsonb),
  ('d2c', 'D2C / E-commerce', 'High-volume consumer demand, conversion, fulfilment and repeat purchase', ARRAY['#4fa8ff','#a855f7','#22c55e','#f0a83f','#2dd4bf']::text[], ARRAY['Fulfilment / Logistics']::text[], '[{"id":"merchandising","label":"Merchandising","color":"#4fa8ff","slot":0,"subNodes":[{"id":"merchandising_assortment","label":"Assortment"},{"id":"merchandising_pricing","label":"Pricing"},{"id":"merchandising_bundles","label":"Bundles"}],"subCycle":{"id":"merchandising_cycle","label":"Merchandising cycle","stages":["Demand signal","Select","Price","Launch","Measure"]}},{"id":"growth_marketing","label":"Growth Mktg","color":"#a855f7","slot":1,"subNodes":[{"id":"growth_marketing_paid_media","label":"Paid media"},{"id":"growth_marketing_creators","label":"Creators"},{"id":"growth_marketing_crm","label":"CRM"}],"subCycle":{"id":"growth_marketing_cycle","label":"Performance growth","stages":["Audience","Creative","Campaign","Convert","Retarget","Optimise"]}},{"id":"commerce","label":"Commerce","color":"#22c55e","slot":2,"subNodes":[{"id":"commerce_storefront","label":"Storefront"},{"id":"commerce_marketplace","label":"Marketplace"},{"id":"commerce_promotions","label":"Promotions"}],"subCycle":{"id":"commerce_cycle","label":"Conversion cycle","stages":["Visit","Browse","Cart","Checkout","Purchase"]}},{"id":"finance","label":"Finance","color":"#f0a83f","slot":3,"subNodes":[{"id":"finance_payments","label":"Payments"},{"id":"finance_refunds","label":"Refunds"},{"id":"finance_margin","label":"Margin"}],"subCycle":{"id":"finance_cycle","label":"Transaction finance","stages":["Collect","Reconcile","Refund","Margin review"]}},{"id":"retention","label":"Retention / CX","color":"#2dd4bf","slot":4,"subNodes":[{"id":"retention_support","label":"Support"},{"id":"retention_loyalty","label":"Loyalty"},{"id":"retention_repeat_purchase","label":"Repeat purchase"}],"subCycle":{"id":"retention_cycle","label":"Retention cycle","stages":["Deliver","Support","Engage","Reorder","Loyalty"]}}]'::jsonb),
  ('manufacturing', 'Manufacturing', 'Channel or enterprise sales backed by production capacity and after-sales support', ARRAY['#4fa8ff','#a855f7','#22c55e','#f0a83f','#2dd4bf']::text[], ARRAY['Distribution','Operations','Supply Chain']::text[], '[{"id":"product_engg","label":"Product / Engg","color":"#4fa8ff","slot":0,"subNodes":[{"id":"product_engg_configuration","label":"Configuration"},{"id":"product_engg_costing","label":"Costing"},{"id":"product_engg_portfolio","label":"Portfolio"}],"subCycle":{"id":"product_engg_cycle","label":"Product commercialisation","stages":["Requirement","Configure","Cost","Validate","Offer"]}},{"id":"marketing","label":"Marketing","color":"#a855f7","slot":1,"subNodes":[{"id":"marketing_industry_campaigns","label":"Industry campaigns"},{"id":"marketing_dealers","label":"Dealers"},{"id":"marketing_exhibitions","label":"Exhibitions"}],"subCycle":{"id":"marketing_cycle","label":"Industrial demand","stages":["Segment","Campaign","Dealer / event","Lead","Nurture"]}},{"id":"sales","label":"Sales","color":"#22c55e","slot":2,"subNodes":[{"id":"sales_direct","label":"Direct"},{"id":"sales_dealer","label":"Dealer"},{"id":"sales_key_accounts","label":"Key accounts"}],"subCycle":{"id":"sales_cycle","label":"Industrial sales","stages":["Lead","Technical need","Quote","Negotiate","Order"]}},{"id":"comm_finance","label":"Commercial Finance","color":"#f0a83f","slot":3,"subNodes":[{"id":"comm_finance_costing","label":"Costing"},{"id":"comm_finance_credit","label":"Credit"},{"id":"comm_finance_billing","label":"Billing"}],"subCycle":{"id":"comm_finance_cycle","label":"Order-to-cash","stages":["Cost","Credit approve","Invoice","Collect","Reconcile"]}},{"id":"service","label":"Service","color":"#2dd4bf","slot":4,"subNodes":[{"id":"service_installation","label":"Installation"},{"id":"service_warranty","label":"Warranty"},{"id":"service_amc","label":"AMC"}],"subCycle":{"id":"service_cycle","label":"After-sales growth","stages":["Install","Commission","Support","Maintain","Upgrade"]}}]'::jsonb),
  ('consulting', 'Professional Services', 'Expertise-led projects, retainers and repeat engagements', ARRAY['#4fa8ff','#a855f7','#22c55e','#f0a83f','#2dd4bf']::text[], ARRAY['Delivery']::text[], '[{"id":"offering","label":"Offering","color":"#4fa8ff","slot":0,"subNodes":[{"id":"offering_service_design","label":"Service design"},{"id":"offering_methodologies","label":"Methodologies"}],"subCycle":{"id":"offering_cycle","label":"Offer development","stages":["Insight","Package","Price","Validate","Refresh"]}},{"id":"marketing","label":"Marketing","color":"#a855f7","slot":1,"subNodes":[{"id":"marketing_thought_leadership","label":"Thought leadership"},{"id":"marketing_events","label":"Events"},{"id":"marketing_referrals","label":"Referrals"}],"subCycle":{"id":"marketing_cycle","label":"Reputation-led marketing","stages":["Publish","Engage","Event / referral","Lead","Nurture"]}},{"id":"biz_dev","label":"Business Dev.","color":"#22c55e","slot":2,"subNodes":[{"id":"biz_dev_advisory_sales","label":"Advisory sales"},{"id":"biz_dev_account_expansion","label":"Account expansion"}],"subCycle":{"id":"biz_dev_cycle","label":"Consultative BD","stages":["Relationship","Diagnose","Scope","Proposal","Negotiate","Win"]}},{"id":"finance","label":"Finance","color":"#f0a83f","slot":3,"subNodes":[{"id":"finance_project_pricing","label":"Project pricing"},{"id":"finance_milestone_invoices","label":"Milestone invoices"}],"subCycle":{"id":"finance_cycle","label":"Professional services billing","stages":["Scope","Price","Contract","Milestone bill","Collect"]}},{"id":"client_success","label":"Client Success","color":"#2dd4bf","slot":4,"subNodes":[{"id":"client_success_delivery_quality","label":"Delivery quality"},{"id":"client_success_relationship","label":"Relationship"},{"id":"client_success_renewal","label":"Renewal"}],"subCycle":{"id":"client_success_cycle","label":"Account growth","stages":["Kickoff","Deliver","Review","Extend","Retainer"]}}]'::jsonb),
  ('education', 'Education / Programmes', 'Institution acquisition, cohort delivery and renewals', ARRAY['#4fa8ff','#a855f7','#22c55e','#f0a83f','#2dd4bf']::text[], ARRAY['Academic Partnerships','Faculty Success','Government Relations']::text[], '[{"id":"programme","label":"Programme","color":"#4fa8ff","slot":0,"subNodes":[{"id":"programme_curriculum","label":"Curriculum"},{"id":"programme_platform","label":"Platform"},{"id":"programme_certification","label":"Certification"}],"subCycle":{"id":"programme_cycle","label":"Programme design","stages":["Need","Design","Validate","Package","Improve"]}},{"id":"inst_marketing","label":"Institutional Mktg","color":"#a855f7","slot":1,"subNodes":[{"id":"inst_marketing_academic_outreach","label":"Academic outreach"},{"id":"inst_marketing_events","label":"Events"},{"id":"inst_marketing_content","label":"Content"}],"subCycle":{"id":"inst_marketing_cycle","label":"Institutional awareness","stages":["Target","Educate","Demo / event","Enquiry","Nurture"]}},{"id":"inst_sales","label":"Institutional Sales","color":"#22c55e","slot":2,"subNodes":[{"id":"inst_sales_university","label":"University"},{"id":"inst_sales_school","label":"School"},{"id":"inst_sales_government","label":"Government"}],"subCycle":{"id":"inst_sales_cycle","label":"Institutional sales","stages":["Lead","Academic discovery","Demo","Proposal","Approval","Agreement"]}},{"id":"finance","label":"Finance","color":"#f0a83f","slot":3,"subNodes":[{"id":"finance_semester_pricing","label":"Semester pricing"},{"id":"finance_bulk_pricing","label":"Bulk pricing"},{"id":"finance_invoicing","label":"Invoicing"}],"subCycle":{"id":"finance_cycle","label":"Institution billing","stages":["Pricing","PO / agreement","Invoice","Collection","Reconcile"]}},{"id":"prog_success","label":"Programme Success","color":"#2dd4bf","slot":4,"subNodes":[{"id":"prog_success_onboarding","label":"Onboarding"},{"id":"prog_success_delivery","label":"Delivery"},{"id":"prog_success_outcomes","label":"Outcomes"}],"subCycle":{"id":"prog_success_cycle","label":"Programme success","stages":["Launch","Train","Deliver","Measure outcomes","Renew"]}}]'::jsonb)
ON CONFLICT (archetype_id) DO UPDATE SET
  label = EXCLUDED.label,
  revenue_model = EXCLUDED.revenue_model,
  slot_colors = EXCLUDED.slot_colors,
  optional_nodes = EXCLUDED.optional_nodes,
  nodes = EXCLUDED.nodes,
  updated_at = now();

