import type { IndustryRecord } from './schema';

/* ================================================================
   12 Work OS Universe Industry Galaxies — as shown in the diagram.
   Each industry has a coreLabel, subdomains, 3D cluster center,
   color, and radius. Company positions are offsets relative to centers.
================================================================ */

export const INDUSTRIES: IndustryRecord[] = [
  {
    id: 'ind-technology',
    label: 'Technology',
    coreLabel: 'TECH CORE',
    description: 'AI, cloud, cybersecurity, hardware, Web3, enterprise software',
    color: '#818cf8',
    position3D: [0, 0, 0],
    bubbleRadius: 14,
    tags: ['b2b', 'global', 'deep-tech', 'high-margin'],
    subdomains: ['AI', 'Cloud', 'Cybersecurity', 'Hardware', 'Web3', 'Enterprise Software', 'Software'],
  },
  {
    id: 'ind-finance',
    label: 'Finance',
    coreLabel: 'FINANCIAL GRAVITY',
    description: 'Fintech, banking, insurance, trading, investing, lending',
    color: '#22d3ee',
    position3D: [-70, -10, -55],
    bubbleRadius: 13,
    tags: ['b2c', 'global', 'regulated', 'capital-markets'],
    subdomains: ['Fintech', 'Banking', 'Insurance', 'Investing', 'Trading', 'Asset Management', 'Lending'],
  },
  {
    id: 'ind-manufacturing',
    label: 'Manufacturing',
    coreLabel: 'INDUSTRIAL ENGINE',
    description: 'Automotive, electronics, industrial machinery, consumer goods',
    color: '#fb923c',
    position3D: [70, 10, -50],
    bubbleRadius: 12,
    tags: ['b2b', 'global', 'capital-intensive', 'operations-heavy'],
    subdomains: ['Automotive', 'Electronics', 'Industrial Machinery', 'Consumer Goods', 'Textiles', 'Supply Chain Systems', 'Heavy Industry'],
  },
  {
    id: 'ind-healthcare',
    label: 'Healthcare',
    coreLabel: 'HEALTH PULSE',
    description: 'Pharma, hospitals, biotech, diagnostics, medical devices',
    color: '#34d399',
    position3D: [-60, 15, 60],
    bubbleRadius: 13,
    tags: ['b2c', 'global', 'regulated', 'ai-driven'],
    subdomains: ['Pharma', 'Biotech', 'Hospitals', 'Diagnostics', 'Preventive Care', 'Mental Health', 'Medical Devices', 'Healthtech'],
  },
  {
    id: 'ind-education',
    label: 'Education',
    coreLabel: 'KNOWLEDGE CORE',
    description: 'Universities, schools, edtech, publishing, skill platforms',
    color: '#a78bfa',
    position3D: [60, 15, 60],
    bubbleRadius: 11,
    tags: ['b2c', 'global', 'consumer', 'impact'],
    subdomains: ['Schools', 'Universities', 'Edtech', 'Test Prep', 'Knowledge Publishing', 'Research Institutions', 'Corporate Training', 'Skill Platforms'],
  },
  {
    id: 'ind-media',
    label: 'Media & Entertainment',
    coreLabel: 'CREATIVE PULSE',
    description: 'Film, TV, streaming, music, gaming, creator economy',
    color: '#f43f5e',
    position3D: [0, -40, -70],
    bubbleRadius: 12,
    tags: ['b2c', 'global', 'ad-driven', 'content'],
    subdomains: ['Film', 'Television', 'Streaming', 'Music', 'Gaming', 'Sports Media', 'Sports Economy', 'Creator Economy'],
  },
  {
    id: 'ind-commerce',
    label: 'Commerce',
    coreLabel: 'COMMERCE FLOW',
    description: 'Retail, e-commerce, D2C brands, marketplaces, wholesale',
    color: '#f472b6',
    position3D: [0, 40, 70],
    bubbleRadius: 12,
    tags: ['b2c', 'global', 'logistics-heavy', 'consumer'],
    subdomains: ['Retail', 'E-commerce', 'D2C Brands', 'Marketplaces', 'Wholesale', 'Consumer Platforms', 'CX Systems'],
  },
  {
    id: 'ind-energy',
    label: 'Energy & Sustainability',
    coreLabel: 'PLANET ENERGY',
    description: 'Solar, wind, storage, EV infrastructure, climate tech',
    color: '#4ade80',
    position3D: [-80, 5, 0],
    bubbleRadius: 11,
    tags: ['global', 'impact', 'capital-intensive', 'climate'],
    subdomains: ['Solar', 'Wind', 'Storage', 'EV Infrastructure', 'Carbon Management', 'Waste Systems', 'Waste Management', 'Climate Tech'],
  },
  {
    id: 'ind-government',
    label: 'Government & Public Systems',
    coreLabel: 'PUBLIC GOOD',
    description: 'Governance, defense, public policy, civic tech, social welfare',
    color: '#64748b',
    position3D: [80, -5, 0],
    bubbleRadius: 10,
    tags: ['b2g', 'global', 'compliance-driven', 'impact'],
    subdomains: ['Governance', 'Defense', 'Public Policy', 'Civic Tech', 'Social Welfare', 'Public Health Systems', 'Social Systems', 'Sust Tech'],
  },
  {
    id: 'ind-mobility',
    label: 'Mobility & Transportation',
    coreLabel: 'MOBILITY NETWORK',
    description: 'Aviation, rail, shipping, automotive mobility, delivery systems, logistics',
    color: '#38bdf8',
    position3D: [0, 80, 0],
    bubbleRadius: 13,
    tags: ['b2c', 'global', 'unit-economics-hard', 'operations-heavy'],
    subdomains: ['Aviation', 'Rail', 'Logistics', 'Shipping', 'Travel Infrastructure', 'Delivery Systems', 'Automotive Mobility'],
  },
  {
    id: 'ind-realestate',
    label: 'Real Estate & Infrastructure',
    coreLabel: 'BUILT WORLD',
    description: 'Commercial, construction, smart buildings, proptech, facility management',
    color: '#fdba74',
    position3D: [50, 55, -40],
    bubbleRadius: 11,
    tags: ['b2c', 'global', 'high-ticket', 'marketplace'],
    subdomains: ['Residential', 'Commercial', 'Construction', 'Facility Management', 'Smart Management', 'Proptech'],
  },
  {
    id: 'ind-agriculture',
    label: 'Agriculture & Food',
    coreLabel: 'GROWTH CYCLE',
    description: 'Farming, agri-tech, food processing, fisheries, nutrition',
    color: '#86efac',
    position3D: [-50, -55, 40],
    bubbleRadius: 10,
    tags: ['b2b', 'global', 'impact', 'rural'],
    subdomains: ['Farming', 'Agri-tech', 'Food Processing', 'Fisheries', 'Supply Delivery', 'Market Discovery'],
  },
];

export const INDUSTRY_MAP = new Map<string, IndustryRecord>(
  INDUSTRIES.map(i => [i.id, i])
);
