import { useCallback, useEffect, useMemo, useState } from 'react';
import { Download, Plus, Trash2 } from 'lucide-react';
import type { Account, CatalogProduct, Deal } from '../../../lib/db/nativeBusiness';
import { nativeBusiness } from '../../../lib/db/nativeBusiness';
import { salesDocuments, type SalesDocument, type SalesDocumentBody, type SalesKind } from '../../../lib/db/salesDocuments';
import { GlassCard } from './PanelShell';

const input='w-full rounded-lg border border-white/10 bg-black/25 px-3 py-2 text-sm text-white outline-none';
const button='rounded-lg border border-white/15 px-3 py-2 text-xs font-semibold text-white/80 hover:bg-white/10 disabled:opacity-40';
const today=()=>new Date().toISOString().slice(0,10);
type DraftLine={productId:string;name:string;description:string;unit:string;quantity:number;unitPrice:number;discountRate:number};
const blankLine=():DraftLine=>({productId:'',name:'',description:'',unit:'unit',quantity:1,unitPrice:0,discountRate:0});
const message=(cause:unknown)=>cause instanceof Error?cause.message:'The operation failed';

function Dialog({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/75 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-white/15 bg-[#111] p-5"><div className="mb-4 flex justify-between"><h3 className="font-semibold">{title}</h3><button className={button} onClick={close}>Close</button></div>{children}</div></div>}

export function NativeSalesDocuments({kind,accounts,deals,canEdit=true,createForDeal,onCreateHandled,onChanged}:{kind:SalesKind;accounts:Account[];deals:Deal[];canEdit?:boolean;createForDeal?:string|null;onCreateHandled?:()=>void;onChanged?:()=>void}){
  const [rows,setRows]=useState<SalesDocument[]>([]); const [selected,setSelected]=useState<SalesDocument|null>(null); const [editing,setEditing]=useState<SalesDocument|null|undefined>(); const [defaultDeal,setDefaultDeal]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const result=await salesDocuments.list(kind);setRows(result.items);setError(null);}catch(cause){setError(message(cause));}finally{setLoading(false)}},[kind]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(createForDeal){setDefaultDeal(createForDeal);setEditing(null);onCreateHandled?.()}},[createForDeal,onCreateHandled]);
  const open=async(row:SalesDocument)=>{try{setSelected(await salesDocuments.get(kind,row.id));setError(null)}catch(cause){setError(message(cause))}};
  const changed=()=>{setSelected(null);setEditing(undefined);void load();onChanged?.()};
  return <GlassCard><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase text-white/50">{kind}</p><p className="text-sm text-white/40">Internal operational documents; totals and snapshots are server-owned.</p></div>{canEdit&&<button className={button} onClick={()=>setEditing(null)}><Plus className="mr-1 inline h-3.5 w-3.5"/>New</button>}</div>
    {error&&<p className="mb-3 rounded-lg bg-rose-400/10 p-2 text-xs text-rose-100">{error}</p>}
    {loading?<p className="text-sm text-white/40">Loading…</p>:rows.length?<div className="space-y-2">{rows.map(row=><button key={row.id} onClick={()=>void open(row)} className="flex w-full items-center justify-between rounded-lg border border-white/10 p-3 text-left"><span><b className="text-sm">{row.document_number}</b><small className="ml-2 text-white/40">{row.account_name}</small></span><span className="text-right"><b className="block text-sm">{row.currency} {Number(row.total).toLocaleString()}</b><small className="text-white/45">{row.status}</small></span></button>)}</div>:<p className="rounded-lg border border-dashed border-white/10 p-8 text-center text-sm text-white/35">No {kind} yet.</p>}
    {editing!==undefined&&<DocumentEditor kind={kind} existing={editing} accounts={accounts} deals={deals} defaultDealId={defaultDeal} close={()=>setEditing(undefined)} saved={changed}/>} 
    {selected&&<DocumentDetail kind={kind} value={selected} canEdit={canEdit} edit={()=>{setEditing(selected);setSelected(null)}} close={()=>setSelected(null)} changed={changed}/>} 
  </GlassCard>;
}

function DocumentEditor({kind,existing,accounts,deals,defaultDealId,close,saved}:{kind:SalesKind;existing:SalesDocument|null;accounts:Account[];deals:Deal[];defaultDealId:string|null;close:()=>void;saved:()=>void}){
  const sourceItems=existing?.items?.map(item=>({productId:item.product_id??'',name:item.name,description:item.description??'',unit:item.unit,quantity:Number(item.quantity),unitPrice:Number(item.unit_price),discountRate:Number(item.discount_rate)}));
  const defaultAccountId=existing?.account_id??deals.find(d=>d.id===defaultDealId)?.account_id??'';
  const [lines,setLines]=useState<DraftLine[]>(sourceItems?.length?sourceItems:[blankLine()]); const [products,setProducts]=useState<CatalogProduct[]>([]); const [seller,setSeller]=useState({name:String(existing?.seller_snapshot?.name??''),email:String(existing?.seller_snapshot?.email??''),address:String(existing?.seller_snapshot?.address??'')}); const initialBuyer=accounts.find(a=>a.id===defaultAccountId); const [buyer,setBuyer]=useState({name:String(existing?.buyer_snapshot?.name??initialBuyer?.name??''),email:String(existing?.buyer_snapshot?.email??initialBuyer?.billing_email??''),address:String(existing?.buyer_snapshot?.address??initialBuyer?.billing_address??'')}); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{void Promise.all([nativeBusiness.products(),salesDocuments.profile()]).then(([result,profile])=>{setProducts(result.items);if(!existing)setSeller({name:profile.seller_name,email:profile.seller_email??'',address:profile.seller_address??''})}).catch(()=>setProducts([]))},[existing]);
  const update=(index:number,patch:Partial<DraftLine>)=>setLines(value=>value.map((line,i)=>i===index?{...line,...patch}:line));
  const choose=(index:number,id:string)=>{const product=products.find(value=>value.id===id);update(index,product?{productId:id,name:product.name,description:product.description??'',unit:product.unit,unitPrice:Number(product.price_amount??0)}:{productId:''})};
  const preview=useMemo(()=>lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice*(1-line.discountRate/100),0),[lines]);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError(null);const data=Object.fromEntries(new FormData(event.currentTarget));const body:SalesDocumentBody={accountId:String(data.accountId),dealId:data.dealId?String(data.dealId):null,issueDate:String(data.issueDate),currency:String(data.currency),seller,buyer,notes:data.notes?String(data.notes):null,terms:data.terms?String(data.terms):null,discountRate:Number(data.discountRate),taxName:data.taxName?String(data.taxName):null,taxRate:Number(data.taxRate),items:lines.map(line=>({productId:line.productId||null,name:line.name,description:line.description||null,unit:line.unit,quantity:line.quantity,unitPrice:line.unitPrice,discountRate:line.discountRate})),...(kind==='quotes'?{validUntil:data.validUntil?String(data.validUntil):null}:kind==='invoices'?{dueDate:data.dueDate?String(data.dueDate):null}:{})};try{if(existing)await salesDocuments.update(kind,existing.id,body);else await salesDocuments.create(kind,body);saved()}catch(cause){setError(message(cause))}finally{setBusy(false)}};
  return <Dialog title={`${existing?'Edit':'New'} ${kind.slice(0,-1)}`} close={close}><form onSubmit={submit} className="space-y-3">{error&&<p className="rounded-lg bg-rose-400/10 p-2 text-xs text-rose-100">{error}</p>}<div className="grid gap-2 md:grid-cols-2"><select name="accountId" required defaultValue={defaultAccountId} onChange={event=>{const account=accounts.find(a=>a.id===event.target.value);if(account)setBuyer({name:account.name,email:account.billing_email??'',address:account.billing_address??''})}} className={input}><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select name="dealId" defaultValue={existing?.deal_id??defaultDealId??''} className={input}><option value="">No deal</option>{deals.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><input name="issueDate" type="date" required defaultValue={existing?.issue_date?.slice(0,10)??today()} className={input}/><input name="currency" required maxLength={3} defaultValue={existing?.currency??'INR'} className={input}/>{kind==='quotes'&&<input name="validUntil" type="date" defaultValue={existing?.valid_until?.slice(0,10)??''} className={input}/>} {kind==='invoices'&&<input name="dueDate" type="date" defaultValue={existing?.due_date?.slice(0,10)??''} className={input}/>}</div><div className="grid gap-3 rounded-lg border border-white/10 p-3 md:grid-cols-2"><div className="space-y-2"><p className="text-xs uppercase text-white/45">Seller snapshot</p><input required value={seller.name} onChange={e=>setSeller({...seller,name:e.target.value})} placeholder="Seller name" className={input}/><input type="email" value={seller.email} onChange={e=>setSeller({...seller,email:e.target.value})} placeholder="Seller email" className={input}/><textarea value={seller.address} onChange={e=>setSeller({...seller,address:e.target.value})} placeholder="Seller address" className={input}/></div><div className="space-y-2"><p className="text-xs uppercase text-white/45">Buyer snapshot</p><input required value={buyer.name} onChange={e=>setBuyer({...buyer,name:e.target.value})} placeholder="Buyer name" className={input}/><input type="email" value={buyer.email} onChange={e=>setBuyer({...buyer,email:e.target.value})} placeholder="Buyer email" className={input}/><textarea value={buyer.address} onChange={e=>setBuyer({...buyer,address:e.target.value})} placeholder="Buyer address" className={input}/></div></div>
    <div className="space-y-2">{lines.map((line,index)=><div key={index} className="rounded-lg border border-white/10 p-3"><div className="grid gap-2 md:grid-cols-2"><select value={line.productId} onChange={e=>choose(index,e.target.value)} className={input}><option value="">Custom line</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><input value={line.name} required placeholder="Item name" onChange={e=>update(index,{name:e.target.value})} className={input}/></div><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-5"><input value={line.unit} required onChange={e=>update(index,{unit:e.target.value})} className={input}/><input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={e=>update(index,{quantity:Number(e.target.value)})} className={input}/><input type="number" min="0" step="0.01" value={line.unitPrice} onChange={e=>update(index,{unitPrice:Number(e.target.value)})} className={input}/><input type="number" min="0" max="100" step="0.01" value={line.discountRate} onChange={e=>update(index,{discountRate:Number(e.target.value)})} className={input}/><button type="button" disabled={lines.length===1} onClick={()=>setLines(value=>value.filter((_,i)=>i!==index))} className={button}><Trash2 className="mx-auto h-3.5 w-3.5"/></button></div></div>)}</div><button type="button" className={button} onClick={()=>setLines(value=>[...value,blankLine()])}>Add custom line</button>
    <div className="grid gap-2 md:grid-cols-3"><input name="discountRate" type="number" min="0" max="100" step="0.01" defaultValue={existing?.discount_rate??0} placeholder="Document discount %" className={input}/><input name="taxName" defaultValue={existing?.tax_name??''} placeholder="Tax name" className={input}/><input name="taxRate" type="number" min="0" max="100" step="0.01" defaultValue={existing?.tax_rate??0} placeholder="Tax %" className={input}/></div><textarea name="notes" defaultValue={existing?.notes??''} placeholder="Notes" className={input}/><textarea name="terms" defaultValue={existing?.terms??''} placeholder="Terms" className={input}/><p className="text-right text-sm text-white/55">Line preview {preview.toFixed(2)} · final totals are calculated by the server</p><button disabled={busy} className={`${button} w-full`}>{busy?'Saving…':'Save draft'}</button></form></Dialog>;
}

function DocumentDetail({kind,value,canEdit,edit,close,changed}:{kind:SalesKind;value:SalesDocument;canEdit:boolean;edit:()=>void;close:()=>void;changed:()=>void}){
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const state=kind==='invoices'?value.state:value.status; const draft=state==='draft';
  const run=async(action:string)=>{setBusy(true);setError(null);try{await salesDocuments.action(kind,value.id,action);changed()}catch(cause){setError(message(cause))}finally{setBusy(false)}};
  const remove=async()=>{if(!window.confirm('Delete this draft?'))return;setBusy(true);try{await salesDocuments.remove(kind,value.id);changed()}catch(cause){setError(message(cause));setBusy(false)}};
  const payment=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);try{await salesDocuments.addPayment(value.id,{amount:Number(data.amount),paidOn:data.paidOn,method:data.method,reference:data.reference||null,note:data.note||null});changed()}catch(cause){setError(message(cause));setBusy(false)}};
  return <Dialog title={`${value.document_number} · ${value.status}`} close={close}>{error&&<p className="mb-3 rounded-lg bg-rose-400/10 p-2 text-xs text-rose-100">{error}</p>}<div className="grid grid-cols-2 gap-2 text-sm md:grid-cols-4"><span>Issue<br/><b>{value.issue_date?.slice(0,10)}</b></span><span>Subtotal<br/><b>{value.currency} {value.subtotal}</b></span><span>Tax<br/><b>{value.tax_amount}</b></span><span>Total<br/><b>{value.currency} {value.total}</b></span></div>{(value.quote_id||value.order_id||value.deal_id)&&<p className="mt-3 text-xs text-white/40">Source: {value.order_id?`order ${value.order_id}`:value.quote_id?`quote ${value.quote_id}`:`deal ${value.deal_id}`}</p>}<div className="my-4 space-y-2">{value.items?.map(item=><div key={item.id??item.name} className="flex justify-between border-b border-white/10 pb-2 text-sm"><span>{item.product_code&&`${item.product_code} · `}{item.name}<small className="ml-2 text-white/40">{item.quantity} × {item.unit_price}</small></span><b>{item.line_total}</b></div>)}</div><div className="flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>void salesDocuments.downloadPdf(kind,value)}><Download className="mr-1 inline h-3.5 w-3.5"/>PDF</button>{canEdit&&draft&&<><button className={button} onClick={edit}>Edit</button><button disabled={busy} className={button} onClick={()=>void remove()}>Delete</button></>}{canEdit&&kind==='quotes'&&state==='draft'&&<button className={button} onClick={()=>void run('send')}>Mark sent</button>}{canEdit&&kind==='quotes'&&['draft','sent'].includes(String(state))&&<button className={button} onClick={()=>void run('cancel')}>Cancel</button>}{canEdit&&kind==='quotes'&&state==='sent'&&<><button className={button} onClick={()=>void run('accept')}>Accept</button><button className={button} onClick={()=>void run('reject')}>Reject</button></>}{canEdit&&kind==='quotes'&&state==='accepted'&&<button className={button} onClick={()=>void run('convert-to-order')}>Create order</button>}{canEdit&&kind==='quotes'&&!draft&&<button className={button} onClick={()=>void run('duplicate')}>Duplicate revision</button>}{canEdit&&kind==='orders'&&state==='draft'&&<button className={button} onClick={()=>void run('confirm')}>Confirm</button>}{canEdit&&kind==='orders'&&['draft','confirmed'].includes(String(state))&&<button className={button} onClick={()=>void run('cancel')}>Cancel</button>}{canEdit&&kind==='orders'&&state==='confirmed'&&<button className={button} onClick={()=>void run('convert-to-invoice')}>Create invoice</button>}{canEdit&&kind==='invoices'&&state==='draft'&&<button className={button} onClick={()=>void run('issue')}>Issue</button>}{canEdit&&kind==='invoices'&&state==='issued'&&<button className={button} onClick={()=>void run('void')}>Void</button>}</div>
    {kind==='invoices'&&<div className="mt-5 border-t border-white/10 pt-4"><p className="mb-2 text-xs font-semibold uppercase text-white/50">Payments · balance {value.currency} {value.balance}</p>{value.payments?.map(p=><div key={p.id} className="mb-2 flex justify-between text-sm"><span>{p.paid_on?.slice(0,10)} · {p.method??'other'} · {p.reference}</span><span>{p.amount} {canEdit&&<button onClick={()=>{void salesDocuments.removePayment(value.id,p.id).then(changed).catch(cause=>setError(message(cause)))}} className="ml-2 text-rose-200">remove</button>}</span></div>)}{canEdit&&state==='issued'&&Number(value.balance)>0&&<form onSubmit={payment} className="mt-3 grid gap-2 md:grid-cols-5"><input name="amount" type="number" min="0.01" max={Number(value.balance)} step="0.01" required placeholder="Amount" className={input}/><input name="paidOn" type="date" defaultValue={today()} required className={input}/><select name="method" className={input}>{['bank','cash','card','other'].map(v=><option key={v}>{v}</option>)}</select><input name="reference" placeholder="Reference" className={input}/><button disabled={busy} className={button}>Add payment</button></form>}</div>}
  </Dialog>;
}
