import { useCallback, useEffect, useMemo, useState } from 'react';
import { Briefcase, Package, Plus, RefreshCw, Trash2, Warehouse } from 'lucide-react';
import {
  nativeBusiness,
  type Account,
  type CatalogGroup,
  type CatalogProduct,
  type CatalogReadiness,
  type Contact,
  type Deal,
  type InventoryBalance,
  type Lead,
} from '../../../lib/db/nativeBusiness';
import { GlassCard, SectionTitle } from './PanelShell';
import { NativeSalesDocuments } from './NativeSalesDocuments';
import { salesDocuments, type SalesSummary } from '../../../lib/db/salesDocuments';

const inputClass = 'w-full rounded-lg border border-white/10 bg-black/25 px-3 py-2 text-sm text-white outline-none';
const buttonClass = 'rounded-lg border border-white/15 px-3 py-2 text-xs font-semibold text-white/80 hover:bg-white/10 disabled:opacity-40';

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-2xl border border-white/15 bg-[#111] p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-white">{title}</h3><button onClick={onClose} className={buttonClass}>Close</button></div>{children}</div></div>;
}

function Empty({ children }: { children: React.ReactNode }) { return <div className="rounded-xl border border-dashed border-white/10 px-4 py-8 text-center text-sm text-white/40">{children}</div>; }
function ErrorLine({ error }: { error: string | null }) { return error ? <p className="mb-3 rounded-lg border border-rose-300/20 bg-rose-300/10 px-3 py-2 text-xs text-rose-100">{error}</p> : null; }
function errorText(error: unknown, fallback: string) { return error instanceof Error ? error.message : fallback; }

type SalesTab = 'pipeline' | 'leads' | 'accounts' | 'contacts' | 'quotes' | 'orders' | 'invoices';
type CrmTab = Exclude<SalesTab, 'quotes' | 'orders' | 'invoices'>;
type SalesItem = Account | Contact | Lead | Deal;

type SalesCapability = 'commercial_customers' | 'commercial_leads' | 'commercial_deals' | 'commercial_quotes' | 'commercial_orders_invoices' | 'commercial_collections';
type CatalogCapability = 'commercial_product_catalogue' | 'commercial_pricing' | 'commercial_inventory';
const salesTabForCapability: Record<SalesCapability, SalesTab> = {
  commercial_customers: 'accounts', commercial_leads: 'leads', commercial_deals: 'pipeline', commercial_quotes: 'quotes', commercial_orders_invoices: 'orders', commercial_collections: 'invoices',
};

export function NativeSalesWorkspace({ canEdit = true, capability }: { canEdit?: boolean; capability?: SalesCapability }) {
  const fixedTab = capability ? salesTabForCapability[capability] : null;
  const [tab, setTab] = useState<SalesTab>(fixedTab ?? 'pipeline');
  useEffect(() => { if (fixedTab) setTab(fixedTab); }, [fixedTab]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [deals, setDeals] = useState<Deal[]>([]);
  const [summary, setSummary] = useState<Awaited<ReturnType<typeof nativeBusiness.summary>> | null>(null);
  const [commercial, setCommercial] = useState<SalesSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editor, setEditor] = useState<{ kind: CrmTab; item?: SalesItem } | null>(null);
  const [quoteDealId, setQuoteDealId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [a, c, l, d, s, commercialSummary] = await Promise.all([nativeBusiness.accounts(), nativeBusiness.contacts(), nativeBusiness.leads(), nativeBusiness.deals(), nativeBusiness.summary(), salesDocuments.summary()]);
      setAccounts(a.items); setContacts(c.items); setLeads(l.items); setDeals(d.items); setSummary(s); setCommercial(commercialSummary); setError(null);
    } catch (cause) { setError(errorText(cause, 'Unable to load native CRM')); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const accountName = (id: string | null) => accounts.find(account => account.id === id)?.name ?? 'Unassigned';
  const stages: Deal['stage'][] = ['qualification', 'discovery', 'proposal', 'negotiation', 'won', 'lost'];
  return <>
    <GlassCard>
      <div className="flex items-start justify-between gap-4"><div><SectionTitle icon={Briefcase}>{capability === 'commercial_customers' ? 'CUSTOMERS & CONTACTS' : capability === 'commercial_leads' ? 'LEAD MANAGEMENT' : capability === 'commercial_deals' ? 'DEAL MANAGEMENT' : capability === 'commercial_quotes' ? 'QUOTATIONS' : capability === 'commercial_orders_invoices' ? 'ORDERS & INVOICES' : capability === 'commercial_collections' ? 'COLLECTIONS' : 'WORKOS CRM'}</SectionTitle><p className="-mt-2 text-sm text-white/50">Native commercial records, scoped to this capability.</p></div><button className={buttonClass} onClick={() => void load()}><RefreshCw className="mr-1 inline h-3.5 w-3.5" />Refresh</button></div>
      <ErrorLine error={error} />
      {summary && <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-5">{Object.entries({ Accounts: summary.metrics.accountCount, Leads: summary.metrics.leadCount, Deals: summary.metrics.dealCount, 'Pipeline value': summary.metrics.openPipelineValue, 'Conversion %': summary.metrics.conversionRate }).map(([label, value]) => <div key={label} className="rounded-lg border border-white/10 bg-white/[.03] p-3"><p className="text-[10px] uppercase text-white/35">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>}
      {commercial && <div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-6">{Object.entries({'Open quotes':commercial.metrics.open_quote_value,'Bookings':commercial.metrics.confirmed_bookings,'Invoiced':commercial.metrics.invoiced_amount,'Collected':commercial.metrics.collected_amount,'Outstanding':commercial.metrics.outstanding_balance,'Overdue':commercial.metrics.overdue_count}).map(([label,value])=><div key={label} className="rounded-lg border border-white/10 bg-white/[.03] p-2"><p className="text-[9px] uppercase text-white/35">{label}</p><p className="text-sm font-semibold">{value}</p></div>)}</div>}
      <div className="mt-5 flex flex-wrap gap-2">{!fixedTab && (['pipeline', 'leads', 'accounts', 'contacts', 'quotes', 'orders', 'invoices'] as SalesTab[]).map(value => <button key={value} onClick={() => setTab(value)} className={`${buttonClass} ${tab === value ? 'bg-violet-400/15 text-violet-100' : ''}`}>{value[0].toUpperCase() + value.slice(1)}</button>)}{canEdit && !['quotes','orders','invoices'].includes(tab) && <button onClick={() => setEditor({ kind: tab as CrmTab })} className={`${buttonClass} ${fixedTab ? '' : 'ml-auto'}`}><Plus className="mr-1 inline h-3.5 w-3.5" />New {tab === 'pipeline' ? 'deal' : tab.slice(0, -1)}</button>}</div>
    </GlassCard>
    {!fixedTab && summary && (summary.recent.length > 0 || summary.recommendations.length > 0) && <div className="grid gap-3 lg:grid-cols-2"><GlassCard><p className="mb-3 text-xs font-semibold uppercase text-white/50">Recent evidence</p><div className="space-y-2">{summary.recent.map(item => <button key={`${item.kind}-${item.id}`} type="button" onClick={() => { const record = item.kind === 'deal' ? deals.find(deal => deal.id === item.id) : leads.find(lead => lead.id === item.id); if (record) setEditor({ kind: item.kind === 'deal' ? 'pipeline' : 'leads', item: record }); }} className="flex w-full items-center justify-between rounded-lg border border-white/10 px-3 py-2 text-left"><span className="text-sm">{item.name}</span><span className="text-xs text-white/40">{item.stage ?? item.status}</span></button>)}</div></GlassCard><GlassCard><p className="mb-3 text-xs font-semibold uppercase text-white/50">Recommended next actions</p>{summary.recommendations.length ? <div className="space-y-2">{summary.recommendations.map(item => <div key={item.code} className="rounded-lg border border-white/10 px-3 py-2"><p className="text-sm font-medium">{item.label}</p><p className="text-xs text-white/45">{item.detail}</p></div>)}</div> : <p className="text-sm text-white/40">No immediate CRM action is recommended.</p>}</GlassCard></div>}
    {loading ? <GlassCard><p className="text-sm text-white/45">Loading CRM…</p></GlassCard> : ['quotes','orders','invoices'].includes(tab) ? <NativeSalesDocuments kind={tab as 'quotes'|'orders'|'invoices'} accounts={accounts} deals={deals} canEdit={canEdit} createForDeal={tab==='quotes'?quoteDealId:null} onCreateHandled={()=>setQuoteDealId(null)} onChanged={load}/> : tab === 'pipeline' ? <div className="grid gap-3 xl:grid-cols-3">{stages.map(stage => <GlassCard key={stage}><p className="mb-3 text-xs font-semibold uppercase tracking-wide text-white/55">{stage}</p><div className="space-y-2">{deals.filter(deal => deal.stage === stage).map(deal => <button key={deal.id} onClick={() => setEditor({ kind: 'pipeline', item: deal })} className="w-full rounded-lg border border-white/10 bg-white/[.03] p-3 text-left"><p className="text-sm font-medium">{deal.name}</p><p className="mt-1 text-xs text-white/45">{accountName(deal.account_id)} · {deal.currency} {Number(deal.value).toLocaleString()}</p></button>)}{!deals.some(deal => deal.stage === stage) && <p className="text-xs text-white/30">No deals</p>}</div></GlassCard>)}</div> : <GlassCard>
      {tab === 'leads' ? (leads.length ? <div className="space-y-2">{leads.map(item => <button key={item.id} onClick={() => setEditor({ kind: 'leads', item })} className="flex w-full justify-between rounded-lg border border-white/10 p-3 text-left"><span><b className="text-sm">{item.name}</b><small className="ml-2 text-white/40">{item.email || item.source}</small></span><span className="text-xs text-white/50">{item.status}</span></button>)}</div> : <Empty>No leads yet.</Empty>) : tab === 'accounts' ? (accounts.length ? <div className="grid gap-2 md:grid-cols-2">{accounts.map(item => <button key={item.id} onClick={() => setEditor({ kind: 'accounts', item })} className="rounded-lg border border-white/10 p-3 text-left"><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-white/45">{item.lifecycle} · {item.industry || 'No industry'}</p></button>)}</div> : <Empty>No accounts yet.</Empty>) : contacts.length ? <div className="grid gap-2 md:grid-cols-2">{contacts.map(item => <button key={item.id} onClick={() => setEditor({ kind: 'contacts', item })} className="rounded-lg border border-white/10 p-3 text-left"><p className="text-sm font-medium">{item.first_name} {item.last_name}</p><p className="text-xs text-white/45">{item.email || item.phone || accountName(item.account_id)}</p></button>)}</div> : <Empty>No contacts yet.</Empty>}
    </GlassCard>}
    {editor && <SalesEditor state={editor} accounts={accounts} canEdit={canEdit} onCreateQuote={deal=>{setEditor(null);setQuoteDealId(deal.id);setTab('quotes')}} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); void load(); }} />}
  </>;
}

function AccountSelect({ accounts, value, required = false }: { accounts: Account[]; value: string; required?: boolean }) {
  return <select name="accountId" defaultValue={value} required={required} className={inputClass}><option value="">{required ? 'Choose account' : 'No account'}</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select>;
}

function SalesEditor({ state, accounts, canEdit, onCreateQuote, onClose, onSaved }: { state: { kind: CrmTab; item?: SalesItem }; accounts: Account[]; canEdit: boolean; onCreateQuote:(deal:Deal)=>void; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const item = state.item as Record<string, unknown> | undefined;
  const run = async (operation: () => Promise<unknown>, fallback: string) => { setBusy(true); setError(null); try { await operation(); onSaved(); } catch (cause) { setError(errorText(cause, fallback)); } finally { setBusy(false); } };
  const save = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget));
    await run(async () => {
      if (state.kind === 'accounts') { const body = { name: data.name, lifecycle: data.lifecycle, industry: data.industry || null, territory: data.territory || null, billingEmail:data.billingEmail||null,billingPhone:data.billingPhone||null,billingAddress:data.billingAddress||null,taxRegistration:data.taxRegistration||null }; await (state.item ? nativeBusiness.updateAccount(state.item.id, body) : nativeBusiness.createAccount(body)); }
      else if (state.kind === 'contacts') { const body = { firstName: data.firstName, lastName: data.lastName || null, email: data.email || null, phone: data.phone || null, accountId: data.accountId || null }; await (state.item ? nativeBusiness.updateContact(state.item.id, body) : nativeBusiness.createContact(body)); }
      else if (state.kind === 'leads') { const body = { name: data.name, email: data.email || null, phone: data.phone || null, source: data.source || null, status: data.status }; await (state.item ? nativeBusiness.updateLead(state.item.id, body) : nativeBusiness.createLead(body)); }
      else { const body = { name: data.name, accountId: data.accountId, value: Number(data.value || 0), currency: data.currency || 'INR', probability: Number(data.probability || 10) }; if (state.item) { await nativeBusiness.updateDeal(state.item.id, body); if (data.stage !== (state.item as Deal).stage) await nativeBusiness.stageDeal(state.item.id, { stage: data.stage, lostReason: data.stage === 'lost' ? data.lostReason || null : null }); } else await nativeBusiness.createDeal({ ...body, stage: data.stage, lostReason: data.stage === 'lost' ? data.lostReason || null : null }); }
    }, 'Save failed');
  };
  const remove = () => run(async () => { if (!state.item) return; if (state.kind === 'accounts') await nativeBusiness.deleteAccount(state.item.id); else if (state.kind === 'contacts') await nativeBusiness.deleteContact(state.item.id); else if (state.kind === 'leads') await nativeBusiness.deleteLead(state.item.id); else await nativeBusiness.deleteDeal(state.item.id); }, 'Delete failed');
  const convert = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (!state.item) return; void run(() => nativeBusiness.convertLead(state.item!.id, { accountId: data.accountId || undefined, accountName: data.accountName || undefined, dealName: data.dealName, value: Number(data.value || 0), currency: data.currency || 'INR' }), 'Lead conversion failed'); };
  const lead = state.kind === 'leads' ? state.item as Lead | undefined : undefined;
  return <Modal title={`${state.item ? 'Edit' : 'New'} ${state.kind === 'pipeline' ? 'deal' : state.kind.slice(0, -1)}`} onClose={onClose}>
    <form onSubmit={save} className="space-y-3"><ErrorLine error={error} />
      {state.kind === 'accounts' ? <><input name="name" defaultValue={String(item?.name ?? '')} required placeholder="Account name" className={inputClass} /><select name="lifecycle" defaultValue={String(item?.lifecycle ?? 'prospect')} className={inputClass}><option value="prospect">Prospect</option><option value="customer">Customer</option><option value="inactive">Inactive</option></select><input name="industry" defaultValue={String(item?.industry ?? '')} placeholder="Industry" className={inputClass} /><input name="territory" defaultValue={String(item?.territory ?? '')} placeholder="Territory" className={inputClass} /></> : state.kind === 'contacts' ? <><input name="firstName" defaultValue={String(item?.first_name ?? '')} required placeholder="First name" className={inputClass} /><input name="lastName" defaultValue={String(item?.last_name ?? '')} placeholder="Last name" className={inputClass} /><input name="email" type="email" defaultValue={String(item?.email ?? '')} placeholder="Email" className={inputClass} /><input name="phone" defaultValue={String(item?.phone ?? '')} placeholder="Phone" className={inputClass} /><AccountSelect accounts={accounts} value={String(item?.account_id ?? '')} /></> : state.kind === 'leads' ? <><input name="name" defaultValue={String(item?.name ?? '')} required placeholder="Lead name" className={inputClass} /><input name="email" type="email" defaultValue={String(item?.email ?? '')} placeholder="Email" className={inputClass} /><input name="source" defaultValue={String(item?.source ?? '')} placeholder="Source" className={inputClass} /><select name="status" defaultValue={String(item?.status ?? 'new')} className={inputClass}>{['new', 'contacted', 'qualified', 'disqualified'].map(value => <option key={value}>{value}</option>)}</select></> : <><input name="name" defaultValue={String(item?.name ?? '')} required placeholder="Deal name" className={inputClass} /><AccountSelect accounts={accounts} value={String(item?.account_id ?? '')} required /><select name="stage" defaultValue={String(item?.stage ?? 'qualification')} className={inputClass}>{['qualification', 'discovery', 'proposal', 'negotiation', 'won', 'lost'].map(value => <option key={value}>{value}</option>)}</select><div className="grid grid-cols-2 gap-2"><input name="value" type="number" min="0" defaultValue={String(item?.value ?? 0)} className={inputClass} /><input name="probability" type="number" min="0" max="100" defaultValue={String(item?.probability ?? 10)} className={inputClass} /></div><input name="currency" defaultValue={String(item?.currency ?? 'INR')} className={inputClass} /><input name="lostReason" placeholder="Lost reason (required when lost)" className={inputClass} /></>}
      {canEdit && <button disabled={busy || lead?.status === 'converted'} className={`${buttonClass} w-full`}>{busy ? 'Saving…' : 'Save'}</button>}
    </form>
    {canEdit&&state.kind==='pipeline'&&state.item&&<button type="button" className={`${buttonClass} mt-3 w-full bg-violet-400/10`} onClick={()=>onCreateQuote(state.item as Deal)}>Create quote from deal</button>}
    {canEdit && lead && lead.status !== 'converted' && <form onSubmit={convert} className="mt-4 space-y-2 border-t border-white/10 pt-4"><p className="text-xs font-semibold uppercase text-white/50">Convert to account and deal</p><AccountSelect accounts={accounts} value={lead.account_id ?? ''} /><input name="accountName" placeholder="Or create account with this name" className={inputClass} /><input name="dealName" required defaultValue={`${lead.name} opportunity`} className={inputClass} /><div className="grid grid-cols-2 gap-2"><input name="value" type="number" min="0" defaultValue="0" className={inputClass} /><input name="currency" defaultValue="INR" className={inputClass} /></div><button disabled={busy} className={`${buttonClass} w-full bg-emerald-400/10`}>Convert lead</button></form>}
    {canEdit && state.item && <button type="button" disabled={busy} onClick={() => { if (window.confirm('Delete this record?')) void remove(); }} className={`${buttonClass} mt-4 w-full text-rose-200`}><Trash2 className="mr-1 inline h-3.5 w-3.5" />Delete</button>}
  </Modal>;
}

export function NativeCatalogWorkspace({ canEdit = true, capability }: { canEdit?: boolean; capability?: CatalogCapability }) {
  const [groups, setGroups] = useState<CatalogGroup[]>([]); const [products, setProducts] = useState<CatalogProduct[]>([]); const [balances, setBalances] = useState<InventoryBalance[]>([]); const [error, setError] = useState<string | null>(null); const [editor, setEditor] = useState<'group' | 'product' | 'stock' | null>(null); const [selected, setSelected] = useState<CatalogProduct | null>(null); const [selectedGroup, setSelectedGroup] = useState<CatalogGroup | null>(null);
  const load = useCallback(async () => { try { const [portfolio, inventory] = await Promise.all([nativeBusiness.portfolio(), nativeBusiness.inventory()]); setGroups(portfolio.groups); setProducts(portfolio.products); setBalances(inventory.items); setError(null); } catch (cause) { setError(errorText(cause, 'Unable to load catalogue')); } }, []);
  useEffect(() => { void load(); }, [load]);
  const grouped = useMemo(() => { const rows: Array<{ group: CatalogGroup; products: CatalogProduct[]; depth: number }> = []; const visit = (parentId: string | null, depth: number) => { for (const group of groups.filter(item => item.parent_id === parentId).sort((a, b) => a.name.localeCompare(b.name))) { rows.push({ group, products: products.filter(product => product.group_id === group.id), depth }); visit(group.id, depth + 1); } }; visit(null, 0); return rows; }, [groups, products]);
  const title = capability === 'commercial_pricing' ? 'PRICING MANAGEMENT' : capability === 'commercial_inventory' ? 'INVENTORY READINESS' : 'PRODUCT CATALOGUE';
  const showGroups = capability !== 'commercial_inventory'; const showProduct = capability !== 'commercial_inventory'; const showStock = capability !== 'commercial_product_catalogue';
  return <><GlassCard><div className="flex items-start justify-between"><div><SectionTitle icon={Package}>{title}</SectionTitle><p className="-mt-2 text-sm text-white/50">Native products, current prices and stock.</p></div><div className="flex gap-2">{canEdit && <>{showGroups && <button className={buttonClass} onClick={() => { setSelectedGroup(null); setEditor('group'); }}><Plus className="mr-1 inline h-3 w-3" />Group</button>}{showProduct && <button className={buttonClass} onClick={() => { setSelected(null); setEditor('product'); }}><Plus className="mr-1 inline h-3 w-3" />Product</button>}{showStock && <button className={buttonClass} disabled={!products.length} onClick={() => setEditor('stock')}><Warehouse className="mr-1 inline h-3 w-3" />Stock</button>}</>}<button className={buttonClass} onClick={() => void load()}><RefreshCw className="h-3.5 w-3.5" /></button></div></div><ErrorLine error={error} /></GlassCard>
    {groups.length === 0 && products.length === 0 ? <GlassCard><Empty>Create a product group and your first product.</Empty></GlassCard> : <div className="space-y-3">{grouped.concat(products.some(product => !product.group_id) ? [{ group: { id: 'ungrouped', name: 'Ungrouped', parent_id: null }, products: products.filter(product => !product.group_id), depth: 0 }] : []).map(({ group, products: items, depth }) => <div key={group.id} style={{ marginLeft: Math.min(depth, 4) * 16 }}><GlassCard><button type="button" disabled={group.id === 'ungrouped'} onClick={() => { if (group.id !== 'ungrouped') { setSelectedGroup(group); setSelected(null); setEditor('group'); } }} className="mb-3 text-left text-xs font-semibold uppercase text-white/50 hover:text-white/80">{depth > 0 ? '↳ ' : ''}{group.name}</button>{items.length ? <div className="grid gap-2 md:grid-cols-2">{items.map(product => { const stock = balances.filter(balance => balance.product_id === product.id).reduce((sum, balance) => sum + Number(balance.quantity), 0); return <button key={product.id} onClick={() => { setSelected(product); setSelectedGroup(null); setEditor('product'); }} className="rounded-lg border border-white/10 p-3 text-left"><div className="flex justify-between"><p className="text-sm font-medium">{product.name}</p><span className={`text-xs ${product.active ? 'text-emerald-200' : 'text-amber-200'}`}>{product.active ? 'Active' : 'Inactive'}</span></div><p className="mt-1 text-xs text-white/45">{product.code} · {product.price_amount == null ? 'Unpriced' : `${product.currency} ${product.price_amount}`} · {stock <= 0 ? 'Zero stock' : stock <= 10 ? `Low stock (${stock})` : `Stock ${stock}`}</p></button>; })}</div> : <p className="text-xs text-white/30">No products in this group.</p>}</GlassCard></div>)}</div>}
    {(selected || selectedGroup) && <CatalogReadinessSummary entity={selected ? 'product' : 'group'} id={(selected ?? selectedGroup)!.id} />}
    {editor && <CatalogEditor kind={editor} group={selectedGroup} product={selected} products={products} groups={groups} canEdit={canEdit} onClose={() => setEditor(null)} onSaved={() => { setEditor(null); void load(); }} />}
  </>;
}

function CatalogReadinessSummary({ entity, id }: { entity: 'group' | 'product'; id: string }) {
  const [readiness, setReadiness] = useState<CatalogReadiness | null>(null);
  useEffect(() => { let current = true; void nativeBusiness.readiness(entity, id).then(value => { if (current) setReadiness(value); }).catch(() => { if (current) setReadiness(null); }); return () => { current = false; }; }, [entity, id]);
  if (!readiness) return null;
  return <GlassCard><p className="text-xs font-semibold uppercase text-white/50">Readiness</p><p className="mt-2 text-sm text-white/60">{readiness.metrics.enabled}/{readiness.metrics.products} enabled · {readiness.metrics.priced} priced · {readiness.metrics.lowStock} low stock · {readiness.metrics.zeroStock} zero stock</p>{readiness.signals.length > 0 && <p className="mt-2 text-xs text-amber-200/80">{readiness.signals.map(signal => signal.label).join(' · ')}</p>}</GlassCard>;
}

function CatalogEditor({ kind, group, product, products, groups, canEdit, onClose, onSaved }: { kind: 'group' | 'product' | 'stock'; group: CatalogGroup | null; product: CatalogProduct | null; products: CatalogProduct[]; groups: CatalogGroup[]; canEdit: boolean; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const run = async (operation: () => Promise<unknown>, fallback: string) => { setBusy(true); setError(null); try { await operation(); onSaved(); } catch (cause) { setError(errorText(cause, fallback)); } finally { setBusy(false); } };
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); await run(async () => { if (kind === 'group') { const body = { name: data.name, parentId: data.parentId || null }; await (group ? nativeBusiness.updateGroup(group.id, body) : nativeBusiness.createGroup(body)); } else if (kind === 'stock') await nativeBusiness.setInventory({ productId: data.productId, warehouseName: data.warehouseName, quantity: Number(data.quantity) }); else { const body = { groupId: data.groupId || null, code: data.code, name: data.name, description: data.description || null, unit: data.unit || 'unit', active: data.active === 'on', priceAmount: data.priceAmount === '' ? null : Number(data.priceAmount), currency: data.currency || null }; await (product ? nativeBusiness.updateProduct(product.id, body) : nativeBusiness.createProduct(body)); } }, 'Save failed'); };
  return <Modal title={kind === 'group' ? `${group ? 'Edit' : 'New'} group` : kind === 'stock' ? 'Set stock' : `${product ? 'Edit' : 'New'} product`} onClose={onClose}><form onSubmit={save} className="space-y-3"><ErrorLine error={error} />{kind === 'group' ? <><input name="name" defaultValue={group?.name ?? ''} required placeholder="Group name" className={inputClass} /><select name="parentId" defaultValue={group?.parent_id ?? ''} className={inputClass}><option value="">Top level</option>{groups.filter(item => item.id !== group?.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></> : kind === 'stock' ? <><select name="productId" required className={inputClass}><option value="">Choose product</option>{products.map(item => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><input name="warehouseName" required placeholder="Warehouse" className={inputClass} /><input name="quantity" type="number" step="0.0001" required className={inputClass} /></> : <><select name="groupId" defaultValue={product?.group_id ?? ''} className={inputClass}><option value="">Ungrouped</option>{groups.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="code" defaultValue={product?.code ?? ''} required placeholder="Product code" className={inputClass} /><input name="name" defaultValue={product?.name ?? ''} required placeholder="Product name" className={inputClass} /><textarea name="description" defaultValue={product?.description ?? ''} placeholder="Description" className={inputClass} /><div className="grid grid-cols-3 gap-2"><input name="unit" defaultValue={product?.unit ?? 'unit'} className={inputClass} /><input name="priceAmount" type="number" min="0" step="0.01" defaultValue={product?.price_amount ?? ''} placeholder="Price" className={inputClass} /><input name="currency" defaultValue={product?.currency ?? 'INR'} className={inputClass} /></div><label className="flex gap-2 text-sm text-white/70"><input name="active" type="checkbox" defaultChecked={product?.active ?? true} />Active</label></>} {canEdit && <button disabled={busy} className={`${buttonClass} w-full`}>{busy ? 'Saving…' : 'Save'}</button>}</form>{canEdit && kind === 'group' && group && <button type="button" disabled={busy} onClick={() => { if (window.confirm('Delete this empty group?')) void run(() => nativeBusiness.deleteGroup(group.id), 'Delete failed'); }} className={`${buttonClass} mt-4 w-full text-rose-200`}><Trash2 className="mr-1 inline h-3.5 w-3.5" />Delete group</button>}{canEdit && kind === 'product' && product && <button type="button" disabled={busy} onClick={() => { if (window.confirm('Delete this product?')) void run(() => nativeBusiness.deleteProduct(product.id), 'Delete failed'); }} className={`${buttonClass} mt-4 w-full text-rose-200`}><Trash2 className="mr-1 inline h-3.5 w-3.5" />Delete product</button>}</Modal>;
}

export function NativeOperationsPlaceholder() { return <GlassCard><SectionTitle icon={Warehouse}>NATIVE OPERATIONS</SectionTitle><p className="text-sm text-white/55">Operations execution is intentionally outside Phase 1. This workspace will use native WorkOS records when that focused module is introduced.</p></GlassCard>; }
