// AUTO-GENERATED by scripts/genBdtSeed.ts - do not edit by hand.
// Regenerate after changing the BDT spec document or catalog metadata.

export type BdtSpecRow = {
  level1Label: string;
  branchItems: string[];
  actionExamples: string[];
  integrations: string[];
  metricImpacts: string[];
};

export type BdtSpecDepartment = {
  departmentLabel: string;
  sourceKey: string;
  rows: BdtSpecRow[];
};

export const BDT_SPEC_TREE: BdtSpecDepartment[] = [
  {
    "departmentLabel": "Engineering",
    "sourceKey": "dept_engineering",
    "rows": [
      {
        "level1Label": "Products & Platforms",
        "branchItems": [
          "Products",
          "services",
          "repositories",
          "technical platforms",
          "internal tools",
          "component ownership"
        ],
        "actionExamples": [
          "Create repository",
          "assign platform owner",
          "open architecture review",
          "link repo to product",
          "create platform roadmap"
        ],
        "integrations": [
          "GitHub/GitLab/Bitbucket",
          "monorepo tools",
          "service catalogues",
          "internal developer portals"
        ],
        "metricImpacts": [
          "Sprint velocity",
          "cycle time",
          "deployment frequency",
          "lead time",
          "defect escape rate"
        ]
      },
      {
        "level1Label": "Development",
        "branchItems": [
          "Backend",
          "frontend",
          "mobile",
          "AI engineering",
          "integrations",
          "QA",
          "automation"
        ],
        "actionExamples": [
          "Create feature ticket",
          "generate test cases",
          "run agent implementation",
          "review PR",
          "assign bug",
          "refactor module"
        ],
        "integrations": [
          "Jira",
          "Linear",
          "GitHub Issues",
          "CI/CD",
          "IDE/Cursor",
          "testing tools"
        ],
        "metricImpacts": [
          "Sprint velocity",
          "cycle time",
          "deployment frequency",
          "lead time",
          "defect escape rate"
        ]
      },
      {
        "level1Label": "Architecture & Quality",
        "branchItems": [
          "System design",
          "APIs",
          "ADRs",
          "code quality",
          "technical debt",
          "documentation",
          "standards"
        ],
        "actionExamples": [
          "Create ADR",
          "approve architecture",
          "generate API docs",
          "schedule tech-debt sprint",
          "enforce code standard"
        ],
        "integrations": [
          "Confluence",
          "Notion",
          "Swagger/OpenAPI",
          "SonarQube",
          "architecture tools"
        ],
        "metricImpacts": [
          "Sprint velocity",
          "cycle time",
          "deployment frequency",
          "lead time",
          "defect escape rate"
        ]
      },
      {
        "level1Label": "Delivery & Operations",
        "branchItems": [
          "Sprints",
          "releases",
          "deployments",
          "DevOps",
          "incidents",
          "observability",
          "reliability"
        ],
        "actionExamples": [
          "Deploy release",
          "rollback",
          "create incident",
          "update release notes",
          "assign on-call",
          "run postmortem"
        ],
        "integrations": [
          "CI/CD",
          "Kubernetes",
          "AWS/Azure/GCP",
          "Datadog",
          "Sentry",
          "PagerDuty"
        ],
        "metricImpacts": [
          "Sprint velocity",
          "cycle time",
          "deployment frequency",
          "lead time",
          "defect escape rate"
        ]
      },
      {
        "level1Label": "Engineering Performance",
        "branchItems": [
          "Velocity",
          "cycle time",
          "defects",
          "uptime",
          "deployment frequency",
          "MTTR",
          "test coverage"
        ],
        "actionExamples": [
          "Improve cycle time",
          "reduce bugs",
          "increase test coverage",
          "unblock sprint",
          "update KR"
        ],
        "integrations": [
          "Analytics from Jira/Linear",
          "GitHub",
          "CI/CD",
          "observability tools"
        ],
        "metricImpacts": [
          "Sprint velocity",
          "cycle time",
          "deployment frequency",
          "lead time",
          "defect escape rate"
        ]
      },
      {
        "level1Label": "Engineering Resources",
        "branchItems": [
          "Cloud budget",
          "licenses",
          "environments",
          "APIs",
          "devices",
          "developer tools",
          "vendor contracts"
        ],
        "actionExamples": [
          "Approve tool",
          "renew license",
          "reduce cloud cost",
          "add environment",
          "allocate compute"
        ],
        "integrations": [
          "Cloud billing",
          "ERP",
          "procurement",
          "vendor tools",
          "license management"
        ],
        "metricImpacts": [
          "Sprint velocity",
          "cycle time",
          "deployment frequency",
          "lead time",
          "defect escape rate"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Product",
    "sourceKey": "dept_product",
    "rows": [
      {
        "level1Label": "Product Portfolio",
        "branchItems": [
          "Products",
          "modules",
          "product lines",
          "feature families",
          "ownership map",
          "lifecycle stage"
        ],
        "actionExamples": [
          "Create product node",
          "assign product owner",
          "retire feature",
          "evaluate portfolio gap",
          "link product to revenue"
        ],
        "integrations": [
          "Productboard",
          "Aha!",
          "Jira Product Discovery",
          "Notion",
          "internal product catalogue"
        ],
        "metricImpacts": [
          "Activation rate",
          "adoption rate",
          "feature usage",
          "retention",
          "churn drivers"
        ]
      },
      {
        "level1Label": "Discovery & Research",
        "branchItems": [
          "User research",
          "interviews",
          "problem statements",
          "insights",
          "hypotheses",
          "market needs"
        ],
        "actionExamples": [
          "Create research plan",
          "schedule interview",
          "summarize feedback",
          "validate hypothesis",
          "generate opportunity brief"
        ],
        "integrations": [
          "Dovetail",
          "Typeform",
          "surveys",
          "call transcripts",
          "CRM feedback"
        ],
        "metricImpacts": [
          "Activation rate",
          "adoption rate",
          "feature usage",
          "retention",
          "churn drivers"
        ]
      },
      {
        "level1Label": "Roadmaps & Releases",
        "branchItems": [
          "Roadmap",
          "releases",
          "epics",
          "milestones",
          "launch plans",
          "prioritization queue"
        ],
        "actionExamples": [
          "Prioritize feature",
          "approve PRD",
          "schedule release",
          "create sprint epic",
          "update roadmap"
        ],
        "integrations": [
          "Jira",
          "Linear",
          "Productboard",
          "release tools",
          "calendar"
        ],
        "metricImpacts": [
          "Activation rate",
          "adoption rate",
          "feature usage",
          "retention",
          "churn drivers"
        ]
      },
      {
        "level1Label": "Customer Insights",
        "branchItems": [
          "Feedback",
          "requests",
          "NPS",
          "churn reasons",
          "support tickets",
          "customer segments"
        ],
        "actionExamples": [
          "Cluster feedback",
          "escalate top pain",
          "create feature request",
          "link request to account",
          "create discovery call"
        ],
        "integrations": [
          "CRM",
          "Intercom",
          "Zendesk",
          "Freshdesk",
          "Gong",
          "NPS tools"
        ],
        "metricImpacts": [
          "Activation rate",
          "adoption rate",
          "feature usage",
          "retention",
          "churn drivers"
        ]
      },
      {
        "level1Label": "Product Performance",
        "branchItems": [
          "Adoption",
          "activation",
          "retention",
          "usage",
          "conversion",
          "feature health",
          "product revenue"
        ],
        "actionExamples": [
          "Investigate drop-off",
          "improve activation",
          "run experiment",
          "update product KR",
          "deprecate low-use feature"
        ],
        "integrations": [
          "Mixpanel",
          "Amplitude",
          "GA4",
          "BI tools",
          "data warehouse"
        ],
        "metricImpacts": [
          "Activation rate",
          "adoption rate",
          "feature usage",
          "retention",
          "churn drivers"
        ]
      },
      {
        "level1Label": "Product Resources",
        "branchItems": [
          "PRDs",
          "specs",
          "design links",
          "analytics",
          "product docs",
          "experiment templates"
        ],
        "actionExamples": [
          "Generate PRD",
          "update spec",
          "attach design",
          "link analytics dashboard",
          "create experiment template"
        ],
        "integrations": [
          "Notion",
          "Confluence",
          "Figma",
          "BI tools",
          "docs"
        ],
        "metricImpacts": [
          "Activation rate",
          "adoption rate",
          "feature usage",
          "retention",
          "churn drivers"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Sales",
    "sourceKey": "dept_sales",
    "rows": [
      {
        "level1Label": "Customers & Accounts",
        "branchItems": [
          "Accounts",
          "contacts",
          "ICP segments",
          "account plans",
          "customer history",
          "buyer committees"
        ],
        "actionExamples": [
          "Create account plan",
          "identify decision maker",
          "schedule meeting",
          "update account status",
          "map buyer committee"
        ],
        "integrations": [
          "Salesforce",
          "HubSpot",
          "Zoho CRM",
          "Pipedrive",
          "LinkedIn Sales Navigator"
        ],
        "metricImpacts": [
          "Revenue",
          "ARR/MRR",
          "bookings",
          "pipeline value",
          "pipeline coverage"
        ]
      },
      {
        "level1Label": "Pipeline & Opportunities",
        "branchItems": [
          "Leads",
          "opportunities",
          "deal stages",
          "pipeline coverage",
          "demos",
          "proposals",
          "negotiations"
        ],
        "actionExamples": [
          "Qualify lead",
          "create opportunity",
          "move stage",
          "send proposal",
          "schedule demo",
          "close deal"
        ],
        "integrations": [
          "CRM",
          "CPQ",
          "calendar",
          "email",
          "proposal tools"
        ],
        "metricImpacts": [
          "Revenue",
          "ARR/MRR",
          "bookings",
          "pipeline value",
          "pipeline coverage"
        ]
      },
      {
        "level1Label": "Revenue Operations",
        "branchItems": [
          "Forecasting",
          "territories",
          "quotas",
          "sales process",
          "CRM hygiene",
          "sales enablement"
        ],
        "actionExamples": [
          "Update forecast",
          "assign territory",
          "clean CRM",
          "create sales play",
          "fix pipeline gap"
        ],
        "integrations": [
          "CRM",
          "RevOps tools",
          "BI",
          "spreadsheet connectors"
        ],
        "metricImpacts": [
          "Revenue",
          "ARR/MRR",
          "bookings",
          "pipeline value",
          "pipeline coverage"
        ]
      },
      {
        "level1Label": "Partnerships & Channels",
        "branchItems": [
          "Resellers",
          "distributors",
          "channel partners",
          "referral partners",
          "alliances"
        ],
        "actionExamples": [
          "Create partner agreement",
          "onboard reseller",
          "track partner lead",
          "prepare co-sell proposal"
        ],
        "integrations": [
          "PartnerStack",
          "CRM",
          "contract tools",
          "partner portals"
        ],
        "metricImpacts": [
          "Revenue",
          "ARR/MRR",
          "bookings",
          "pipeline value",
          "pipeline coverage"
        ]
      },
      {
        "level1Label": "Sales Performance",
        "branchItems": [
          "Revenue",
          "bookings",
          "win rate",
          "conversion",
          "sales cycle",
          "quota attainment",
          "pipeline health"
        ],
        "actionExamples": [
          "Improve win rate",
          "shorten sales cycle",
          "update quota KR",
          "identify underperforming segment"
        ],
        "integrations": [
          "CRM analytics",
          "BI dashboards",
          "forecasting tools"
        ],
        "metricImpacts": [
          "Revenue",
          "ARR/MRR",
          "bookings",
          "pipeline value",
          "pipeline coverage"
        ]
      },
      {
        "level1Label": "Sales Resources",
        "branchItems": [
          "Decks",
          "case studies",
          "price sheets",
          "proposal templates",
          "battlecards",
          "scripts"
        ],
        "actionExamples": [
          "Generate deck",
          "update pricing sheet",
          "create battlecard",
          "approve discount",
          "share case study"
        ],
        "integrations": [
          "Docs",
          "enablement tools",
          "proposal software",
          "CRM assets"
        ],
        "metricImpacts": [
          "Revenue",
          "ARR/MRR",
          "bookings",
          "pipeline value",
          "pipeline coverage"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Marketing",
    "sourceKey": "dept_marketing",
    "rows": [
      {
        "level1Label": "Paid Acquisition",
        "branchItems": [
          "Ad Performance",
          "Spend & Reach",
          "Campaigns"
        ],
        "actionExamples": [
          "Configure conversion goal",
          "Review spend pacing",
          "Launch campaign"
        ],
        "integrations": [
          "Meta Ads",
          "Google Ads"
        ],
        "metricImpacts": [
          "ROAS, CAC, Ad Leads",
          "Ad spend, impressions, CTR, CPC",
          "Campaign-level spend and ROAS"
        ]
      },
      {
        "level1Label": "Organic Growth",
        "branchItems": [
          "Not yet connected"
        ],
        "actionExamples": [
          "Connect an organic growth integration"
        ],
        "integrations": [
          "GA4",
          "Search Console"
        ],
        "metricImpacts": [
          "Awaiting integration"
        ]
      },
      {
        "level1Label": "Demand & Attribution",
        "branchItems": [
          "Pipeline Attribution"
        ],
        "actionExamples": [
          "Connect CRM to attribute pipeline to ad spend"
        ],
        "integrations": [
          "CRM",
          "Meta Ads"
        ],
        "metricImpacts": [
          "Awaiting CRM integration"
        ]
      },
      {
        "level1Label": "Brand & Intelligence",
        "branchItems": [
          "Not yet connected"
        ],
        "actionExamples": [
          "Connect a brand or market intelligence integration"
        ],
        "integrations": [
          "Similarweb",
          "SEMrush",
          "brand tools"
        ],
        "metricImpacts": [
          "Awaiting integration"
        ]
      }
    ]
  },
  {
    "departmentLabel": "People & HR",
    "sourceKey": "dept_hr",
    "rows": [
      {
        "level1Label": "Talent Acquisition",
        "branchItems": [
          "Open roles",
          "candidates",
          "interviews",
          "hiring pipeline",
          "offers",
          "onboarding handoff"
        ],
        "actionExamples": [
          "Create job description",
          "shortlist candidate",
          "schedule interview",
          "send offer",
          "close role"
        ],
        "integrations": [
          "ATS",
          "LinkedIn Recruiter",
          "calendar",
          "email",
          "assessment platforms"
        ],
        "metricImpacts": [
          "Time-to-hire",
          "offer acceptance rate",
          "hiring funnel conversion",
          "attrition",
          "retention"
        ]
      },
      {
        "level1Label": "People Operations",
        "branchItems": [
          "Employee records",
          "attendance",
          "leave",
          "payroll inputs",
          "policies",
          "lifecycle events"
        ],
        "actionExamples": [
          "Approve leave",
          "update employee record",
          "process payroll input",
          "issue policy",
          "manage exit"
        ],
        "integrations": [
          "HRIS",
          "payroll",
          "attendance",
          "ERP",
          "document systems"
        ],
        "metricImpacts": [
          "Time-to-hire",
          "offer acceptance rate",
          "hiring funnel conversion",
          "attrition",
          "retention"
        ]
      },
      {
        "level1Label": "Learning & Development",
        "branchItems": [
          "Training",
          "skills",
          "learning paths",
          "certifications",
          "leadership development"
        ],
        "actionExamples": [
          "Assign course",
          "create training plan",
          "track certification",
          "schedule workshop",
          "map skill gap"
        ],
        "integrations": [
          "LMS",
          "Coursera/Udemy",
          "internal academy",
          "HRIS"
        ],
        "metricImpacts": [
          "Time-to-hire",
          "offer acceptance rate",
          "hiring funnel conversion",
          "attrition",
          "retention"
        ]
      },
      {
        "level1Label": "Culture & Engagement",
        "branchItems": [
          "Engagement surveys",
          "recognition",
          "rituals",
          "wellbeing",
          "internal communication"
        ],
        "actionExamples": [
          "Launch survey",
          "create engagement plan",
          "recognize employee",
          "schedule townhall",
          "address issue"
        ],
        "integrations": [
          "Survey tools",
          "Slack/Teams",
          "HRIS",
          "wellbeing tools"
        ],
        "metricImpacts": [
          "Time-to-hire",
          "offer acceptance rate",
          "hiring funnel conversion",
          "attrition",
          "retention"
        ]
      },
      {
        "level1Label": "Workforce Performance",
        "branchItems": [
          "Performance reviews",
          "capacity",
          "attrition",
          "productivity",
          "manager effectiveness"
        ],
        "actionExamples": [
          "Start review cycle",
          "set performance goal",
          "identify attrition risk",
          "rebalance capacity"
        ],
        "integrations": [
          "HRIS",
          "performance management tools",
          "project data"
        ],
        "metricImpacts": [
          "Time-to-hire",
          "offer acceptance rate",
          "hiring funnel conversion",
          "attrition",
          "retention"
        ]
      },
      {
        "level1Label": "HR Resources",
        "branchItems": [
          "Policies",
          "org charts",
          "compensation bands",
          "benefits",
          "templates",
          "HR budget"
        ],
        "actionExamples": [
          "Update policy",
          "approve benefit",
          "adjust compensation band",
          "create onboarding checklist"
        ],
        "integrations": [
          "HRIS",
          "docs",
          "compensation tools",
          "ERP"
        ],
        "metricImpacts": [
          "Time-to-hire",
          "offer acceptance rate",
          "hiring funnel conversion",
          "attrition",
          "retention"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Finance",
    "sourceKey": "dept_finance",
    "rows": [
      {
        "level1Label": "Financial Operations",
        "branchItems": [
          "Accounting",
          "invoicing",
          "collections",
          "payroll payments",
          "reconciliations",
          "closing"
        ],
        "actionExamples": [
          "Raise invoice",
          "approve payment",
          "reconcile account",
          "close month",
          "follow up receivable"
        ],
        "integrations": [
          "Tally",
          "QuickBooks",
          "Zoho Books",
          "ERP",
          "bank feeds",
          "payment gateways"
        ],
        "metricImpacts": [
          "Revenue",
          "gross margin",
          "EBITDA",
          "cashflow",
          "burn rate"
        ]
      },
      {
        "level1Label": "Planning & Forecasting",
        "branchItems": [
          "Budgets",
          "forecasts",
          "scenarios",
          "runway",
          "financial plans",
          "department allocation"
        ],
        "actionExamples": [
          "Create forecast",
          "update budget",
          "run scenario",
          "adjust runway plan",
          "allocate department budget"
        ],
        "integrations": [
          "ERP",
          "FP&A tools",
          "spreadsheets",
          "BI"
        ],
        "metricImpacts": [
          "Revenue",
          "gross margin",
          "EBITDA",
          "cashflow",
          "burn rate"
        ]
      },
      {
        "level1Label": "Treasury & Capital",
        "branchItems": [
          "Cash",
          "bank accounts",
          "debt",
          "equity",
          "grants",
          "fundraising",
          "investment tracking"
        ],
        "actionExamples": [
          "Move funds",
          "update cash position",
          "prepare fundraising pack",
          "track debt repayment"
        ],
        "integrations": [
          "Bank portals",
          "ERP",
          "cap table tools",
          "investor CRM"
        ],
        "metricImpacts": [
          "Revenue",
          "gross margin",
          "EBITDA",
          "cashflow",
          "burn rate"
        ]
      },
      {
        "level1Label": "Procurement & Spend",
        "branchItems": [
          "Purchase requests",
          "vendors",
          "spend approvals",
          "contracts",
          "expense controls"
        ],
        "actionExamples": [
          "Approve purchase",
          "compare vendors",
          "reduce spend",
          "renew subscription",
          "flag overspend"
        ],
        "integrations": [
          "ERP",
          "procurement tools",
          "expense systems",
          "vendor portals"
        ],
        "metricImpacts": [
          "Revenue",
          "gross margin",
          "EBITDA",
          "cashflow",
          "burn rate"
        ]
      },
      {
        "level1Label": "Compliance & Audit",
        "branchItems": [
          "Tax",
          "GST",
          "statutory filings",
          "audit evidence",
          "financial controls",
          "documentation"
        ],
        "actionExamples": [
          "Prepare GST data",
          "upload audit evidence",
          "validate control",
          "close compliance task"
        ],
        "integrations": [
          "Tally/ERP",
          "GST portal",
          "audit tools",
          "document management"
        ],
        "metricImpacts": [
          "Revenue",
          "gross margin",
          "EBITDA",
          "cashflow",
          "burn rate"
        ]
      },
      {
        "level1Label": "Financial Performance",
        "branchItems": [
          "Revenue",
          "margin",
          "burn",
          "runway",
          "EBITDA",
          "cashflow",
          "budget variance",
          "unit economics"
        ],
        "actionExamples": [
          "Improve margin",
          "reduce burn",
          "update cashflow KR",
          "identify variance",
          "optimize CAC payback"
        ],
        "integrations": [
          "BI",
          "accounting system",
          "CRM",
          "payment systems"
        ],
        "metricImpacts": [
          "Revenue",
          "gross margin",
          "EBITDA",
          "cashflow",
          "burn rate"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Operations",
    "sourceKey": "dept_operations",
    "rows": [
      {
        "level1Label": "Service Delivery",
        "branchItems": [
          "Delivery processes",
          "SLAs",
          "service requests",
          "fulfillment",
          "field operations"
        ],
        "actionExamples": [
          "Assign delivery owner",
          "resolve SLA breach",
          "create delivery plan",
          "update status"
        ],
        "integrations": [
          "ERP",
          "service desk",
          "field ops tools",
          "project systems"
        ],
        "metricImpacts": [
          "SLA adherence",
          "throughput",
          "cycle time",
          "fulfillment rate",
          "error rate"
        ]
      },
      {
        "level1Label": "Supply Chain & Logistics",
        "branchItems": [
          "Inventory",
          "logistics",
          "shipping",
          "warehousing",
          "routing",
          "procurement flow"
        ],
        "actionExamples": [
          "Create shipment",
          "update inventory",
          "optimize route",
          "raise procurement request"
        ],
        "integrations": [
          "ERP",
          "inventory systems",
          "logistics platforms",
          "WMS"
        ],
        "metricImpacts": [
          "SLA adherence",
          "throughput",
          "cycle time",
          "fulfillment rate",
          "error rate"
        ]
      },
      {
        "level1Label": "Vendors & Procurement",
        "branchItems": [
          "Vendor onboarding",
          "POs",
          "contracts",
          "quality",
          "service levels",
          "renewals"
        ],
        "actionExamples": [
          "Onboard vendor",
          "create PO",
          "review vendor performance",
          "renew contract"
        ],
        "integrations": [
          "ERP",
          "procurement tools",
          "vendor management systems"
        ],
        "metricImpacts": [
          "SLA adherence",
          "throughput",
          "cycle time",
          "fulfillment rate",
          "error rate"
        ]
      },
      {
        "level1Label": "Process Excellence",
        "branchItems": [
          "SOPs",
          "automation",
          "quality improvement",
          "bottlenecks",
          "workflows",
          "lean processes"
        ],
        "actionExamples": [
          "Update SOP",
          "automate process",
          "remove bottleneck",
          "create improvement project"
        ],
        "integrations": [
          "BPM tools",
          "RPA",
          "docs",
          "workflow platforms"
        ],
        "metricImpacts": [
          "SLA adherence",
          "throughput",
          "cycle time",
          "fulfillment rate",
          "error rate"
        ]
      },
      {
        "level1Label": "Operational Performance",
        "branchItems": [
          "SLA adherence",
          "cost",
          "quality",
          "throughput",
          "cycle time",
          "utilization",
          "error rate"
        ],
        "actionExamples": [
          "Reduce cycle time",
          "improve SLA",
          "update operations KR",
          "resolve quality issue"
        ],
        "integrations": [
          "ERP analytics",
          "BI",
          "service tools",
          "project data"
        ],
        "metricImpacts": [
          "SLA adherence",
          "throughput",
          "cycle time",
          "fulfillment rate",
          "error rate"
        ]
      },
      {
        "level1Label": "Operational Resources",
        "branchItems": [
          "Facilities",
          "equipment",
          "tools",
          "assets",
          "budgets",
          "licenses",
          "operating capacity"
        ],
        "actionExamples": [
          "Allocate facility",
          "approve equipment",
          "maintain asset",
          "schedule inspection"
        ],
        "integrations": [
          "Asset management",
          "ERP",
          "facility tools"
        ],
        "metricImpacts": [
          "SLA adherence",
          "throughput",
          "cycle time",
          "fulfillment rate",
          "error rate"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Data & Analytics",
    "sourceKey": "dept_data",
    "rows": [
      {
        "level1Label": "Data Engineering",
        "branchItems": [
          "Pipelines",
          "warehouses",
          "ETL/ELT",
          "data quality",
          "integrations",
          "data models"
        ],
        "actionExamples": [
          "Create pipeline",
          "fix data issue",
          "sync source",
          "build warehouse table",
          "document schema"
        ],
        "integrations": [
          "Snowflake",
          "BigQuery",
          "Databricks",
          "Airflow",
          "dbt",
          "Fivetran"
        ],
        "metricImpacts": [
          "Data freshness",
          "data quality score",
          "pipeline uptime",
          "dashboard adoption",
          "report usage"
        ]
      },
      {
        "level1Label": "Business Intelligence",
        "branchItems": [
          "Dashboards",
          "reports",
          "metric definitions",
          "executive views",
          "self-service analytics"
        ],
        "actionExamples": [
          "Create dashboard",
          "update metric definition",
          "publish report",
          "fix visualization"
        ],
        "integrations": [
          "Power BI",
          "Tableau",
          "Looker",
          "Metabase",
          "BI tools"
        ],
        "metricImpacts": [
          "Data freshness",
          "data quality score",
          "pipeline uptime",
          "dashboard adoption",
          "report usage"
        ]
      },
      {
        "level1Label": "Analytics & Insights",
        "branchItems": [
          "Analysis",
          "experiments",
          "cohorts",
          "attribution",
          "forecasting",
          "recommendations"
        ],
        "actionExamples": [
          "Run analysis",
          "generate insight memo",
          "create cohort",
          "evaluate experiment",
          "suggest action"
        ],
        "integrations": [
          "Python/R",
          "notebooks",
          "BI",
          "analytics platforms"
        ],
        "metricImpacts": [
          "Data freshness",
          "data quality score",
          "pipeline uptime",
          "dashboard adoption",
          "report usage"
        ]
      },
      {
        "level1Label": "AI & Models",
        "branchItems": [
          "ML models",
          "prediction engines",
          "recommendation systems",
          "LLM workflows",
          "model monitoring"
        ],
        "actionExamples": [
          "Train model",
          "deploy model",
          "evaluate drift",
          "improve prompt",
          "run model audit"
        ],
        "integrations": [
          "MLflow",
          "Vertex AI",
          "SageMaker",
          "OpenAI/LLM APIs",
          "vector DBs"
        ],
        "metricImpacts": [
          "Data freshness",
          "data quality score",
          "pipeline uptime",
          "dashboard adoption",
          "report usage"
        ]
      },
      {
        "level1Label": "Data Governance",
        "branchItems": [
          "Access",
          "privacy",
          "lineage",
          "catalogues",
          "definitions",
          "compliance",
          "master data"
        ],
        "actionExamples": [
          "Approve access",
          "classify data",
          "update lineage",
          "resolve duplicate source"
        ],
        "integrations": [
          "Data catalogue",
          "IAM",
          "governance tools",
          "DLP"
        ],
        "metricImpacts": [
          "Data freshness",
          "data quality score",
          "pipeline uptime",
          "dashboard adoption",
          "report usage"
        ]
      },
      {
        "level1Label": "Data Performance",
        "branchItems": [
          "Freshness",
          "accuracy",
          "query speed",
          "adoption",
          "insight impact",
          "model quality"
        ],
        "actionExamples": [
          "Improve data freshness",
          "reduce query latency",
          "increase dashboard adoption",
          "fix metric inconsistency"
        ],
        "integrations": [
          "Data observability",
          "BI usage analytics",
          "warehouse monitoring"
        ],
        "metricImpacts": [
          "Data freshness",
          "data quality score",
          "pipeline uptime",
          "dashboard adoption",
          "report usage"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Design",
    "sourceKey": "dept_design",
    "rows": [
      {
        "level1Label": "Design Systems",
        "branchItems": [
          "Components",
          "tokens",
          "patterns",
          "guidelines",
          "accessibility",
          "reusable design assets"
        ],
        "actionExamples": [
          "Create component",
          "update token",
          "publish guideline",
          "audit accessibility",
          "sync with frontend"
        ],
        "integrations": [
          "Figma",
          "Storybook",
          "design token tools",
          "docs"
        ],
        "metricImpacts": [
          "Usability score",
          "design cycle time",
          "design debt",
          "component reuse",
          "accessibility compliance"
        ]
      },
      {
        "level1Label": "UX Research",
        "branchItems": [
          "User interviews",
          "usability tests",
          "journey maps",
          "personas",
          "insights",
          "research repository"
        ],
        "actionExamples": [
          "Schedule test",
          "summarize insight",
          "create journey map",
          "validate pain point"
        ],
        "integrations": [
          "Dovetail",
          "Maze",
          "Typeform",
          "call recording",
          "docs"
        ],
        "metricImpacts": [
          "Usability score",
          "design cycle time",
          "design debt",
          "component reuse",
          "accessibility compliance"
        ]
      },
      {
        "level1Label": "Product Design",
        "branchItems": [
          "Flows",
          "wireframes",
          "prototypes",
          "screens",
          "interaction states",
          "product experiences"
        ],
        "actionExamples": [
          "Create prototype",
          "handoff design",
          "revise flow",
          "link design to PRD",
          "test usability"
        ],
        "integrations": [
          "Figma",
          "Miro/FigJam",
          "Zeplin",
          "Jira/Linear"
        ],
        "metricImpacts": [
          "Usability score",
          "design cycle time",
          "design debt",
          "component reuse",
          "accessibility compliance"
        ]
      },
      {
        "level1Label": "Brand & Visual Design",
        "branchItems": [
          "Identity",
          "graphics",
          "decks",
          "collateral",
          "visual direction",
          "campaign design"
        ],
        "actionExamples": [
          "Create visual asset",
          "approve deck",
          "update brand guideline",
          "design campaign creative"
        ],
        "integrations": [
          "Figma",
          "Adobe",
          "Canva",
          "DAM"
        ],
        "metricImpacts": [
          "Usability score",
          "design cycle time",
          "design debt",
          "component reuse",
          "accessibility compliance"
        ]
      },
      {
        "level1Label": "Design Performance",
        "branchItems": [
          "Usability",
          "design debt",
          "adoption",
          "accessibility score",
          "handoff quality",
          "cycle time"
        ],
        "actionExamples": [
          "Reduce design debt",
          "improve accessibility",
          "update UX KR",
          "fix low-conversion flow"
        ],
        "integrations": [
          "Product analytics",
          "accessibility tools",
          "design reviews"
        ],
        "metricImpacts": [
          "Usability score",
          "design cycle time",
          "design debt",
          "component reuse",
          "accessibility compliance"
        ]
      },
      {
        "level1Label": "Design Resources",
        "branchItems": [
          "Design files",
          "asset libraries",
          "templates",
          "research repo",
          "licenses",
          "budget"
        ],
        "actionExamples": [
          "Organize library",
          "renew license",
          "publish template",
          "archive old design file"
        ],
        "integrations": [
          "Figma libraries",
          "DAM",
          "procurement/ERP"
        ],
        "metricImpacts": [
          "Usability score",
          "design cycle time",
          "design debt",
          "component reuse",
          "accessibility compliance"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Security",
    "sourceKey": "dept_security",
    "rows": [
      {
        "level1Label": "Identity & Access",
        "branchItems": [
          "Users",
          "roles",
          "permissions",
          "MFA",
          "privileged access",
          "access reviews"
        ],
        "actionExamples": [
          "Grant access",
          "revoke access",
          "run access review",
          "enforce MFA",
          "investigate privilege risk"
        ],
        "integrations": [
          "Okta",
          "Azure AD",
          "Google Workspace",
          "IAM",
          "SSO"
        ],
        "metricImpacts": [
          "Critical vulnerabilities",
          "mean time to detect/respond",
          "patch SLA",
          "incident count",
          "access review completion"
        ]
      },
      {
        "level1Label": "Infrastructure Security",
        "branchItems": [
          "Cloud posture",
          "network security",
          "endpoints",
          "hardening",
          "vulnerability management"
        ],
        "actionExamples": [
          "Patch vulnerability",
          "update firewall rule",
          "audit cloud posture",
          "isolate endpoint"
        ],
        "integrations": [
          "Cloud security tools",
          "EDR",
          "SIEM",
          "CSPM"
        ],
        "metricImpacts": [
          "Critical vulnerabilities",
          "mean time to detect/respond",
          "patch SLA",
          "incident count",
          "access review completion"
        ]
      },
      {
        "level1Label": "Application Security",
        "branchItems": [
          "Code scanning",
          "app vulnerabilities",
          "secrets",
          "APIs",
          "secure SDLC",
          "penetration testing"
        ],
        "actionExamples": [
          "Run scan",
          "fix vulnerability",
          "rotate secret",
          "schedule pentest",
          "approve secure release"
        ],
        "integrations": [
          "Snyk",
          "SonarQube",
          "GitHub Security",
          "Burp",
          "API security tools"
        ],
        "metricImpacts": [
          "Critical vulnerabilities",
          "mean time to detect/respond",
          "patch SLA",
          "incident count",
          "access review completion"
        ]
      },
      {
        "level1Label": "Monitoring & Incident Response",
        "branchItems": [
          "Alerts",
          "incidents",
          "logs",
          "investigations",
          "response plans",
          "postmortems"
        ],
        "actionExamples": [
          "Create incident",
          "escalate alert",
          "contain breach",
          "run postmortem",
          "update playbook"
        ],
        "integrations": [
          "SIEM",
          "Datadog",
          "Splunk",
          "PagerDuty",
          "incident tools"
        ],
        "metricImpacts": [
          "Critical vulnerabilities",
          "mean time to detect/respond",
          "patch SLA",
          "incident count",
          "access review completion"
        ]
      },
      {
        "level1Label": "Governance & Compliance",
        "branchItems": [
          "Policies",
          "audits",
          "risk registers",
          "certifications",
          "compliance controls",
          "training"
        ],
        "actionExamples": [
          "Update policy",
          "collect evidence",
          "close audit finding",
          "assign security training"
        ],
        "integrations": [
          "GRC tools",
          "audit tools",
          "LMS",
          "document management"
        ],
        "metricImpacts": [
          "Critical vulnerabilities",
          "mean time to detect/respond",
          "patch SLA",
          "incident count",
          "access review completion"
        ]
      },
      {
        "level1Label": "Security Performance",
        "branchItems": [
          "Risk score",
          "vulnerabilities",
          "incidents",
          "patch SLA",
          "compliance status",
          "awareness"
        ],
        "actionExamples": [
          "Reduce risk",
          "close critical vuln",
          "improve patch SLA",
          "update security KR"
        ],
        "integrations": [
          "Security dashboards",
          "SIEM",
          "GRC",
          "vulnerability scanners"
        ],
        "metricImpacts": [
          "Critical vulnerabilities",
          "mean time to detect/respond",
          "patch SLA",
          "incident count",
          "access review completion"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Customer Success",
    "sourceKey": "dept_customer_success",
    "rows": [
      {
        "level1Label": "Customer Accounts",
        "branchItems": [
          "Customer portfolio",
          "segments",
          "health scores",
          "success plans",
          "stakeholders"
        ],
        "actionExamples": [
          "Create success plan",
          "update health score",
          "map stakeholder",
          "schedule QBR"
        ],
        "integrations": [
          "Gainsight",
          "Totango",
          "CRM",
          "CSM tools"
        ],
        "metricImpacts": [
          "Net revenue retention",
          "gross retention",
          "churn",
          "expansion revenue",
          "product adoption"
        ]
      },
      {
        "level1Label": "Onboarding & Adoption",
        "branchItems": [
          "Onboarding plans",
          "implementation",
          "training",
          "usage adoption",
          "activation"
        ],
        "actionExamples": [
          "Start onboarding",
          "assign training",
          "resolve adoption blocker",
          "create usage plan"
        ],
        "integrations": [
          "CS platform",
          "LMS",
          "product analytics",
          "calendar"
        ],
        "metricImpacts": [
          "Net revenue retention",
          "gross retention",
          "churn",
          "expansion revenue",
          "product adoption"
        ]
      },
      {
        "level1Label": "Support & Service",
        "branchItems": [
          "Tickets",
          "escalations",
          "SLAs",
          "knowledge base",
          "support workflows"
        ],
        "actionExamples": [
          "Resolve ticket",
          "escalate issue",
          "update KB",
          "assign support owner",
          "close SLA risk"
        ],
        "integrations": [
          "Zendesk",
          "Freshdesk",
          "Intercom",
          "Jira Service Management"
        ],
        "metricImpacts": [
          "Net revenue retention",
          "gross retention",
          "churn",
          "expansion revenue",
          "product adoption"
        ]
      },
      {
        "level1Label": "Retention & Expansion",
        "branchItems": [
          "Renewals",
          "upsell",
          "cross-sell",
          "churn risk",
          "expansion opportunities"
        ],
        "actionExamples": [
          "Prepare renewal",
          "identify upsell",
          "address churn risk",
          "create expansion proposal"
        ],
        "integrations": [
          "CRM",
          "CS platform",
          "billing",
          "proposal tools"
        ],
        "metricImpacts": [
          "Net revenue retention",
          "gross retention",
          "churn",
          "expansion revenue",
          "product adoption"
        ]
      },
      {
        "level1Label": "Customer Performance",
        "branchItems": [
          "Health score",
          "adoption",
          "NRR",
          "churn",
          "CSAT",
          "NPS",
          "support metrics"
        ],
        "actionExamples": [
          "Improve health score",
          "reduce churn",
          "update NRR KR",
          "increase product usage"
        ],
        "integrations": [
          "CS analytics",
          "CRM",
          "product analytics",
          "support tools"
        ],
        "metricImpacts": [
          "Net revenue retention",
          "gross retention",
          "churn",
          "expansion revenue",
          "product adoption"
        ]
      },
      {
        "level1Label": "CS Resources",
        "branchItems": [
          "Playbooks",
          "onboarding templates",
          "training content",
          "KB",
          "customer collateral"
        ],
        "actionExamples": [
          "Update playbook",
          "create training deck",
          "publish KB article",
          "upload QBR template"
        ],
        "integrations": [
          "Knowledge base",
          "docs",
          "LMS",
          "asset libraries"
        ],
        "metricImpacts": [
          "Net revenue retention",
          "gross retention",
          "churn",
          "expansion revenue",
          "product adoption"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Legal & Compliance",
    "sourceKey": "dept_legal",
    "rows": [
      {
        "level1Label": "Contracts & Agreements",
        "branchItems": [
          "Customer contracts",
          "vendor contracts",
          "NDAs",
          "MSAs",
          "SOWs",
          "renewal terms"
        ],
        "actionExamples": [
          "Review contract",
          "approve clause",
          "generate NDA",
          "track renewal",
          "flag legal risk"
        ],
        "integrations": [
          "CLM tools",
          "DocuSign",
          "CRM/ERP",
          "document management"
        ],
        "metricImpacts": [
          "Contract turnaround time",
          "compliance status",
          "open legal risks",
          "dispute count",
          "regulatory deadline adherence"
        ]
      },
      {
        "level1Label": "Regulatory Compliance",
        "branchItems": [
          "Statutory requirements",
          "sector regulations",
          "filings",
          "licenses",
          "policies"
        ],
        "actionExamples": [
          "Create compliance task",
          "upload filing",
          "update license",
          "map regulation to controls"
        ],
        "integrations": [
          "GRC tools",
          "compliance portals",
          "legal databases"
        ],
        "metricImpacts": [
          "Contract turnaround time",
          "compliance status",
          "open legal risks",
          "dispute count",
          "regulatory deadline adherence"
        ]
      },
      {
        "level1Label": "IP & Data Rights",
        "branchItems": [
          "Patents",
          "trademarks",
          "copyrights",
          "data rights",
          "licensing",
          "ownership"
        ],
        "actionExamples": [
          "File trademark",
          "review IP clause",
          "update data processing agreement",
          "register asset"
        ],
        "integrations": [
          "IP management tools",
          "CLM",
          "document systems"
        ],
        "metricImpacts": [
          "Contract turnaround time",
          "compliance status",
          "open legal risks",
          "dispute count",
          "regulatory deadline adherence"
        ]
      },
      {
        "level1Label": "Legal Advisory & Disputes",
        "branchItems": [
          "Legal opinions",
          "disputes",
          "litigation",
          "notices",
          "advisory requests"
        ],
        "actionExamples": [
          "Draft legal opinion",
          "respond to notice",
          "assign counsel",
          "update dispute risk"
        ],
        "integrations": [
          "Legal matter management",
          "email",
          "document management"
        ],
        "metricImpacts": [
          "Contract turnaround time",
          "compliance status",
          "open legal risks",
          "dispute count",
          "regulatory deadline adherence"
        ]
      },
      {
        "level1Label": "Legal Performance & Risk",
        "branchItems": [
          "Contract cycle time",
          "risk exposure",
          "open legal issues",
          "compliance gaps"
        ],
        "actionExamples": [
          "Reduce cycle time",
          "close compliance gap",
          "update risk register",
          "improve approval SLA"
        ],
        "integrations": [
          "CLM analytics",
          "GRC",
          "legal dashboards"
        ],
        "metricImpacts": [
          "Contract turnaround time",
          "compliance status",
          "open legal risks",
          "dispute count",
          "regulatory deadline adherence"
        ]
      },
      {
        "level1Label": "Legal Resources",
        "branchItems": [
          "Templates",
          "policies",
          "clause library",
          "counsel network",
          "legal budget"
        ],
        "actionExamples": [
          "Update clause library",
          "approve template",
          "allocate legal budget",
          "renew counsel engagement"
        ],
        "integrations": [
          "CLM",
          "docs",
          "ERP/procurement"
        ],
        "metricImpacts": [
          "Contract turnaround time",
          "compliance status",
          "open legal risks",
          "dispute count",
          "regulatory deadline adherence"
        ]
      }
    ]
  },
  {
    "departmentLabel": "Strategy",
    "sourceKey": "dept_strategy",
    "rows": [
      {
        "level1Label": "Corporate Strategy",
        "branchItems": [
          "Vision",
          "strategic priorities",
          "business model",
          "annual plan",
          "company thesis"
        ],
        "actionExamples": [
          "Update strategic plan",
          "define priority",
          "create strategy memo",
          "align department goals"
        ],
        "integrations": [
          "Docs",
          "planning tools",
          "OKR systems",
          "board packs"
        ],
        "metricImpacts": [
          "Strategic objective progress",
          "initiative ROI",
          "market expansion progress",
          "portfolio balance",
          "strategic risk index"
        ]
      },
      {
        "level1Label": "Growth Initiatives",
        "branchItems": [
          "New markets",
          "new products",
          "strategic programs",
          "expansion bets",
          "transformation projects"
        ],
        "actionExamples": [
          "Create growth initiative",
          "evaluate market",
          "assign owner",
          "approve experiment",
          "scale initiative"
        ],
        "integrations": [
          "Project systems",
          "CRM",
          "market research",
          "BI"
        ],
        "metricImpacts": [
          "Strategic objective progress",
          "initiative ROI",
          "market expansion progress",
          "portfolio balance",
          "strategic risk index"
        ]
      },
      {
        "level1Label": "Market Intelligence",
        "branchItems": [
          "Industry trends",
          "competitor moves",
          "customer shifts",
          "macro signals",
          "regulatory changes"
        ],
        "actionExamples": [
          "Create market memo",
          "update competitor signal",
          "identify opportunity",
          "brief leadership"
        ],
        "integrations": [
          "Research tools",
          "web/news feeds",
          "CRM",
          "BI",
          "IDT"
        ],
        "metricImpacts": [
          "Strategic objective progress",
          "initiative ROI",
          "market expansion progress",
          "portfolio balance",
          "strategic risk index"
        ]
      },
      {
        "level1Label": "Partnerships & M&A",
        "branchItems": [
          "Strategic partners",
          "alliances",
          "acquisitions",
          "investments",
          "ecosystem mapping"
        ],
        "actionExamples": [
          "Shortlist partner",
          "start diligence",
          "create partnership proposal",
          "evaluate acquisition target"
        ],
        "integrations": [
          "CRM",
          "deal tools",
          "data rooms",
          "legal/finance systems"
        ],
        "metricImpacts": [
          "Strategic objective progress",
          "initiative ROI",
          "market expansion progress",
          "portfolio balance",
          "strategic risk index"
        ]
      },
      {
        "level1Label": "Strategic Performance",
        "branchItems": [
          "Strategic KPIs",
          "objective progress",
          "initiative ROI",
          "execution confidence"
        ],
        "actionExamples": [
          "Update strategy KR",
          "rebalance portfolio",
          "kill weak initiative",
          "escalate strategic risk"
        ],
        "integrations": [
          "OKR tools",
          "BI",
          "project systems",
          "USIM-style simulator"
        ],
        "metricImpacts": [
          "Strategic objective progress",
          "initiative ROI",
          "market expansion progress",
          "portfolio balance",
          "strategic risk index"
        ]
      },
      {
        "level1Label": "Strategic Resources",
        "branchItems": [
          "Board decks",
          "strategy templates",
          "market reports",
          "budgets",
          "advisors",
          "strategic data"
        ],
        "actionExamples": [
          "Generate board update",
          "upload report",
          "allocate initiative budget",
          "engage advisor"
        ],
        "integrations": [
          "Docs",
          "BI",
          "ERP",
          "investor/board portals"
        ],
        "metricImpacts": [
          "Strategic objective progress",
          "initiative ROI",
          "market expansion progress",
          "portfolio balance",
          "strategic risk index"
        ]
      }
    ]
  }
];
