import PDFDocument from 'pdfkit';

type PdfDocument = Record<string, unknown> & { document_number: string; currency: string; issue_date: string; due_date?: string | null; valid_until?: string | null; status?: string; state?: string; seller_snapshot: Record<string,unknown>; buyer_snapshot: Record<string,unknown>; items: Array<Record<string,unknown>>; subtotal: string; discount_amount: string; tax_name?: string | null; tax_rate: string; tax_amount: string; total: string; notes?: string | null; terms?: string | null };

function snapshotLines(snapshot: Record<string,unknown>) {
  return [snapshot.name, snapshot.email, snapshot.phone, snapshot.address, snapshot.registration, snapshot.tax_registration].filter(Boolean).map(String);
}

export function renderSalesDocumentPdf(kind: 'quote'|'order'|'invoice', record: PdfDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const pdf = new PDFDocument({ margin: 44, size: 'A4' });
    const chunks: Buffer[] = [];
    pdf.on('data', chunk => chunks.push(Buffer.from(chunk)));
    pdf.on('error', reject);
    pdf.on('end', () => resolve(Buffer.concat(chunks)));
    const title = kind === 'quote' ? 'QUOTE' : kind === 'order' ? 'SALES ORDER' : 'INVOICE';
    pdf.fontSize(21).text(title, { align: 'right' }).fontSize(10).fillColor('#555').text(record.document_number, { align: 'right' });
    pdf.moveDown().fillColor('#111').fontSize(10);
    const seller = snapshotLines(record.seller_snapshot); const buyer = snapshotLines(record.buyer_snapshot);
    pdf.font('Helvetica-Bold').text('From'); pdf.font('Helvetica').text(seller.join('\n') || 'Seller details not configured');
    pdf.moveUp(Math.max(1, seller.length)).font('Helvetica-Bold').text('Bill to', 320); pdf.font('Helvetica').text(buyer.join('\n') || 'Buyer', 320);
    pdf.moveDown(2).font('Helvetica').text(`Issue date: ${record.issue_date}`);
    if (record.valid_until) pdf.text(`Valid until: ${record.valid_until}`);
    if (record.due_date) pdf.text(`Due date: ${record.due_date}`);
    pdf.text(`Status: ${String(record.status ?? record.state ?? '').toUpperCase()}`);
    pdf.moveDown().font('Helvetica-Bold');
    const columns = [44, 260, 330, 395, 470];
    ['Item','Qty','Unit price','Discount','Total'].forEach((label,index)=>pdf.text(label,columns[index],pdf.y,{width:index===0?200:70}));
    pdf.moveDown().font('Helvetica');
    for (const item of record.items) {
      const y = pdf.y; pdf.text(String(item.name),columns[0],y,{width:205}); pdf.text(String(item.quantity),columns[1],y,{width:60}); pdf.text(String(item.unit_price),columns[2],y,{width:60}); pdf.text(`${item.discount_rate}%`,columns[3],y,{width:60}); pdf.text(String(item.line_total),columns[4],y,{width:70,align:'right'}); pdf.moveDown();
    }
    pdf.moveDown().text(`Subtotal: ${record.currency} ${record.subtotal}`,350,undefined,{align:'right'});
    if (Number(record.discount_amount)>0) pdf.text(`Discount: -${record.currency} ${record.discount_amount}`,350,undefined,{align:'right'});
    if (Number(record.tax_amount)>0) pdf.text(`${record.tax_name || 'Tax'} (${record.tax_rate}%): ${record.currency} ${record.tax_amount}`,350,undefined,{align:'right'});
    pdf.font('Helvetica-Bold').fontSize(12).text(`Total: ${record.currency} ${record.total}`,350,undefined,{align:'right'}).font('Helvetica').fontSize(10);
    if (record.notes) { pdf.moveDown(2).font('Helvetica-Bold').text('Notes'); pdf.font('Helvetica').text(record.notes); }
    if (record.terms) { pdf.moveDown().font('Helvetica-Bold').text('Terms'); pdf.font('Helvetica').text(record.terms); }
    pdf.fontSize(8).fillColor('#666').text('Operational commercial document generated by WorkOS. Verify all tax, legal, and statutory requirements independently.',44,760,{width:507,align:'center'});
    pdf.end();
  });
}
