import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { after, before, describe, test } from 'node:test';
import express from 'express';
import { createClient } from '@supabase/supabase-js';
import { env } from '../src/config.js';
import { pool, supabaseAdmin } from '../src/db.js';
import { initializeRbac } from '../src/rbac.js';
import { salesRouter } from '../src/domains/sales/router.js';

const dbDescribe=process.env.SALES_DOCUMENT_DB_TESTS==='1'?describe:describe.skip;
dbDescribe('native quote-to-cash against disposable local Postgres',{concurrency:1},()=>{
  const suffix=randomUUID().slice(0,8); const companies:string[]=[]; const users:string[]=[]; const tokens:string[]=[]; let baseUrl=''; let server:ReturnType<ReturnType<typeof express>['listen']>;
  async function tenant(index:number){const company=await pool.query(`insert into public.companies(name,slug,stage,country,description,status,is_public,offset_3d,currency) values($1,$2,'Seed','India','Sales test','active',false,'{}','INR') returning id`,[`Sales ${suffix} ${index}`,`sales-${suffix}-${index}`]);const companyId=String(company.rows[0].id);const email=`sales-${suffix}-${index}@example.com`;const password=`Sales-${suffix}-${index}-safe-123!`;const created=await supabaseAdmin.auth.admin.createUser({email,password,email_confirm:true});if(created.error||!created.data.user)throw created.error;const userId=created.data.user.id;await pool.query(`insert into public.user_profiles(id,company_id,role,first_name,onboarding_completed) values($1,$2,'super_admin','Sales',true)`,[userId,companyId]);await pool.query(`insert into public.company_members(company_id,user_id,role,status,approved_at) values($1,$2,'super_admin','active',now())`,[companyId,userId]);const client=createClient(env.SUPABASE_URL,env.SUPABASE_ANON_KEY,{auth:{persistSession:false}});const signed=await client.auth.signInWithPassword({email,password});if(signed.error||!signed.data.session)throw signed.error;companies.push(companyId);users.push(userId);tokens.push(signed.data.session.access_token);}
  async function request(index:number,method:string,path:string,body?:unknown){const response=await fetch(`${baseUrl}${path}`,{method,headers:{authorization:`Bearer ${tokens[index]}`,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const buffer=Buffer.from(await response.arrayBuffer());const contentType=response.headers.get('content-type')??'';return {status:response.status,body:contentType.includes('json')&&buffer.length?JSON.parse(buffer.toString()):buffer};}
  before(async()=>{const url=new URL(env.DATABASE_URL.replace(/^postgresql:/,'postgres:'));assert.ok(['127.0.0.1','localhost'].includes(url.hostname),'sales tests refuse non-local DATABASE_URL');await tenant(0);await tenant(1);await initializeRbac();const app=express();app.use(express.json());app.use('/api/sales',salesRouter);server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('missing address');baseUrl=`http://127.0.0.1:${address.port}`;});
  after(async()=>{if(server)await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));for(const id of companies)await pool.query('delete from public.companies where id=$1',[id]);for(const id of users)await supabaseAdmin.auth.admin.deleteUser(id);await pool.end();});

  test('ACLs and cross-company references are backend-only and tenant-safe',async()=>{const grants=await pool.query(`select table_name from information_schema.role_table_grants where table_schema='public' and grantee in ('anon','authenticated') and table_name like 'sales_%'`);assert.deepEqual(grants.rows,[]);const foreign=await pool.query(`insert into public.crm_accounts(company_id,name) values($1,'Foreign') returning id`,[companies[1]]);const invalid=await request(0,'POST','/api/sales/quotes',{accountId:foreign.rows[0].id,issueDate:'2026-08-10',currency:'INR',discountRate:0,taxRate:0,items:[{name:'Custom',quantity:1,unitPrice:10,discountRate:0}]});assert.equal(invalid.status,404);});

  test('quote acceptance, immutable snapshots, conversions, payments, summary and PDF',async()=>{const account=(await pool.query(`insert into public.crm_accounts(company_id,name,billing_email,billing_address) values($1,'Acme','billing@acme.test','Bengaluru') returning id`,[companies[0]])).rows[0];const deal=(await pool.query(`insert into public.crm_deals(company_id,account_id,name,value,currency) values($1,$2,'Acme deal',1000,'INR') returning id`,[companies[0],account.id])).rows[0];const product=(await pool.query(`insert into public.catalog_products(company_id,code,name,unit,price_amount,currency) values($1,'PLAN','Plan','month',333.335,'INR') returning id`,[companies[0]])).rows[0];const inventory=(await pool.query(`insert into public.inventory_balances(company_id,product_id,warehouse_name,quantity) values($1,$2,'Main',9) returning quantity`,[companies[0],product.id])).rows[0].quantity;
    const quote=await request(0,'POST','/api/sales/quotes',{accountId:account.id,dealId:deal.id,issueDate:'2026-08-10',validUntil:'2026-08-20',currency:'INR',discountRate:10,taxName:'Operational tax',taxRate:5,items:[{productId:product.id,quantity:3,discountRate:2},{name:'Setup',unit:'job',quantity:1,unitPrice:100.005,discountRate:0}]});assert.equal(quote.status,201);assert.equal(quote.body.subtotal,'1080.03');assert.equal(quote.body.discount_amount,'108.00');assert.equal(quote.body.tax_amount,'48.60');assert.equal(quote.body.total,'1020.63');assert.match(quote.body.document_number,/^Q-2026-0001$/);assert.equal(quote.body.items[0].name,'Plan');
    await pool.query(`update public.catalog_products set name='Changed',price_amount=1 where company_id=$1 and id=$2`,[companies[0],product.id]);const snapshot=await request(0,'GET',`/api/sales/quotes/${quote.body.id}`);assert.equal(snapshot.body.items[0].name,'Plan');assert.equal(Number(snapshot.body.items[0].unit_price),333.34);
    assert.equal((await request(0,'POST',`/api/sales/quotes/${quote.body.id}/send`,{})).status,200);assert.equal((await request(0,'PUT',`/api/sales/quotes/${quote.body.id}`,{accountId:account.id,issueDate:'2026-08-10',currency:'INR',discountRate:0,taxRate:0,items:[{name:'x',quantity:1,unitPrice:1,discountRate:0}]})).status,409);assert.equal((await request(0,'POST',`/api/sales/quotes/${quote.body.id}/accept`,{})).status,200);assert.equal((await pool.query(`select stage from public.crm_deals where id=$1`,[deal.id])).rows[0].stage,'won');assert.equal((await pool.query(`select lifecycle from public.crm_accounts where id=$1`,[account.id])).rows[0].lifecycle,'customer');
    const order=await request(0,'POST',`/api/sales/quotes/${quote.body.id}/convert-to-order`,{});assert.equal(order.status,201);assert.equal((await request(0,'POST',`/api/sales/quotes/${quote.body.id}/convert-to-order`,{})).status,409);assert.equal((await request(0,'POST',`/api/sales/orders/${order.body.id}/confirm`,{})).status,200);const invoice=await request(0,'POST',`/api/sales/orders/${order.body.id}/convert-to-invoice`,{});assert.equal(invoice.status,201);assert.equal((await request(0,'POST',`/api/sales/invoices/${invoice.body.id}/issue`,{})).status,200);
    assert.equal(invoice.body.issue_date,'2026-08-10');
    const firstPayment=await request(0,'POST',`/api/sales/invoices/${invoice.body.id}/payments`,{amount:400,paidOn:'2026-08-11',method:'bank',reference:'BANK-1'});assert.equal(firstPayment.status,201);const partial=await request(0,'GET',`/api/sales/invoices/${invoice.body.id}`);assert.equal(partial.body.status,'partial');assert.equal(partial.body.balance,'620.63');assert.equal((await request(0,'POST',`/api/sales/invoices/${invoice.body.id}/payments`,{amount:621,paidOn:'2026-08-11'})).status,409);const final=await request(0,'POST',`/api/sales/invoices/${invoice.body.id}/payments`,{amount:620.63,paidOn:'2026-08-11',method:'bank'});assert.equal(final.status,201);assert.equal((await request(0,'GET',`/api/sales/invoices/${invoice.body.id}`)).body.status,'paid');assert.equal((await request(0,'POST',`/api/sales/invoices/${invoice.body.id}/void`,{})).status,409);
    const pdf=await request(0,'GET',`/api/sales/invoices/${invoice.body.id}/pdf`);assert.equal(pdf.status,200);assert.equal(pdf.body.subarray(0,5).toString(),'%PDF-');const summary=await request(0,'GET','/api/sales/summary');assert.equal(summary.body.metrics.confirmed_bookings,1020.63);assert.equal(summary.body.metrics.invoiced_amount,1020.63);assert.equal(summary.body.metrics.collected_amount,1020.63);assert.equal(summary.body.metrics.outstanding_balance,0);assert.equal(Number((await pool.query(`select quantity from public.inventory_balances where company_id=$1 and product_id=$2`,[companies[0],product.id])).rows[0].quantity),Number(inventory));assert.equal((await request(0,'DELETE',`/api/sales/invoices/${invoice.body.id}/payments/${firstPayment.body.id}`)).status,204);assert.equal((await request(0,'DELETE',`/api/sales/invoices/${invoice.body.id}/payments/${final.body.id}`)).status,204);assert.equal((await request(0,'POST',`/api/sales/invoices/${invoice.body.id}/void`,{})).status,200);
  });

  test('expired quote is derived and cannot be accepted',async()=>{const account=(await pool.query(`insert into public.crm_accounts(company_id,name) values($1,'Expired buyer') returning id`,[companies[0]])).rows[0];const quote=await request(0,'POST','/api/sales/quotes',{accountId:account.id,issueDate:'2020-01-01',validUntil:'2020-01-02',currency:'INR',discountRate:0,taxRate:0,items:[{name:'Old',quantity:1,unitPrice:10,discountRate:0}]});await request(0,'POST',`/api/sales/quotes/${quote.body.id}/send`,{});assert.equal((await request(0,'GET',`/api/sales/quotes/${quote.body.id}`)).body.status,'expired');assert.equal((await request(0,'POST',`/api/sales/quotes/${quote.body.id}/accept`,{})).status,409);});

  test('concurrent document creation allocates unique company/year numbers',async()=>{const account=(await pool.query(`insert into public.crm_accounts(company_id,name) values($1,'Concurrent buyer') returning id`,[companies[0]])).rows[0];const body={accountId:account.id,issueDate:'2027-01-01',currency:'INR',discountRate:0,taxRate:0,items:[{name:'Seat',quantity:1,unitPrice:1,discountRate:0}]};const created=await Promise.all(Array.from({length:8},()=>request(0,'POST','/api/sales/quotes',body)));assert.ok(created.every(row=>row.status===201));const numbers=created.map(row=>row.body.document_number);assert.equal(new Set(numbers).size,8);assert.deepEqual(numbers.map(value=>Number(String(value).split('-').at(-1))).sort((a,b)=>a-b),[1,2,3,4,5,6,7,8]);});
});
