import React, { useState } from 'react';
import { Plus } from 'lucide-react';
import type { ImplementationTask, TaskStatus } from '../types';
import { useObjectSpaceContext } from '../utils/useObjectSpaceContext';

const domainLabel = (domain: string) => (domain ? domain.charAt(0).toUpperCase() + domain.slice(1) : 'General');

interface CreateTaskModalProps {
  isOpen: boolean;
  currentUser?: { name: string; email: string };
  onCreateTask: (task: ImplementationTask) => void;
  onClose: () => void;
}

const STATUS_CONFIG: { id: TaskStatus; label: string; activeClass: string; inactiveClass: string; dotClass: string }[] = [
  {
    id: 'active',
    label: 'Active',
    activeClass: 'bg-purple-600 border-purple-600 text-white shadow-xs font-bold',
    inactiveClass: 'bg-slate-900 border-slate-800 text-slate-400 hover:text-purple-300 hover:bg-slate-850',
    dotClass: 'bg-purple-500',
  },
  {
    id: 'in_progress',
    label: 'In Progress',
    activeClass: 'bg-blue-600 border-blue-600 text-white shadow-xs font-bold',
    inactiveClass: 'bg-slate-900 border-slate-800 text-slate-400 hover:text-blue-300 hover:bg-slate-850',
    dotClass: 'bg-blue-500',
  },
  {
    id: 'completed',
    label: 'Completed',
    activeClass: 'bg-emerald-600 border-emerald-600 text-white shadow-xs font-bold',
    inactiveClass: 'bg-slate-900 border-slate-800 text-slate-400 hover:text-emerald-300 hover:bg-slate-850',
    dotClass: 'bg-emerald-500',
  },
];

export const CreateTaskModal: React.FC<CreateTaskModalProps> = ({
  isOpen,
  currentUser = { name: 'Ronak', email: 'manager@example.com' },
  onCreateTask,
  onClose,
}) => {
  const getTodayDateString = () => {
    try {
      return new Date().toISOString().slice(0, 10);
    } catch {
      return '2026-10-04';
    }
  };

  const [title, setTitle] = useState('');
  const [status, setStatus] = useState<TaskStatus>('active');
  const [goal, setGoal] = useState('');
  const [dueDate, setDueDate] = useState(getTodayDateString());
  const [dueTime, setDueTime] = useState('18:00');
  const [estimatedMinutes, setEstimatedMinutes] = useState(60);
  const ctx = useObjectSpaceContext(isOpen);

  const departments = ctx.status === 'ready' ? ctx.data.departments : [];
  const defaultDeptId = ctx.status === 'ready' ? ctx.data.me.departmentId ?? '' : '';
  const [departmentId, setDepartmentId] = useState('');
  const [departmentText, setDepartmentText] = useState('');
  const [jobTitle, setJobTitle] = useState('');

  // Pre-fill once when the context resolves.
  React.useEffect(() => {
    if (ctx.status !== 'ready') return;
    if (defaultDeptId && !departmentId) setDepartmentId(defaultDeptId);
    if (ctx.data.me.jobTitle && !jobTitle) setJobTitle(ctx.data.me.jobTitle);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ctx.status]);

  React.useEffect(() => {
    if (isOpen) {
      document.body.classList.add('modal-open');
    }
    return () => {
      document.body.classList.remove('modal-open');
    };
  }, [isOpen]);

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    const chosenDept = departments.find((d) => d.id === departmentId);
    const departmentName = (chosenDept?.label || departmentText).trim();
    if (!departmentName) return;
    if (!jobTitle.trim()) return;

    const formattedDue = `${dueDate} at ${dueTime}`;
    const generatedId = `task-${Date.now()}`;

    const newTask: ImplementationTask = {
      id: generatedId,
      title: title.trim(),
      departmentKey: chosenDept?.id || departmentName.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
      departmentName,
      category: chosenDept ? domainLabel(chosenDept.domain) : 'General Operations',
      goal: goal.trim() || 'Execute standard operating procedure and achieve target deliverable.',
      priority: 'medium',
      status,
      // Job title is what the AI playbook uses to pitch the steps at the right level.
      assignee: { id: 'user-manager', name: currentUser.name, email: currentUser.email, role: jobTitle.trim() },
      createdBy: currentUser.email,
      createdByName: `${currentUser.name} (Owner)`,
      objectType: 'OPPORTUNITY',
      due: formattedDue,
      estimatedMinutes: Number(estimatedMinutes) || 60,
      progress: status === 'completed' ? 100 : status === 'in_progress' ? 40 : 0,
      // Steps are generated by the AI playbook the first time the task is opened.
      steps: [],
      playbook: { status: 'pending' },
    };

    onCreateTask(newTask);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-fadeIn font-sans">
      {/* Modal Card with dark theme and hidden scrollbars */}
      <div className="relative w-full max-w-lg bg-[#0c101d] text-slate-100 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header - color-coordinated with the dark universe interface */}
        <div className="px-6 pt-6 pb-2 bg-[#0c101d] flex items-center justify-between shrink-0">
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base font-bold tracking-tight text-white">Create Object Task</h2>
              <span className="text-[10px] font-mono font-medium px-2 py-0.5 rounded-full bg-violet-950/80 text-violet-300">
                Object Space
              </span>
            </div>
            <p className="text-[11px] text-slate-400 mt-0.5">
              Personal task assignment with AI playbook generation
            </p>
          </div>
        </div>

        {/* Live Form with hidden scrollbar */}
        <form
          onSubmit={handleSubmit}
          className="p-6 space-y-4 overflow-y-auto [scrollbar-width:none] [-ms-overflow-style:none] [&::-webkit-scrollbar]:hidden flex-1 text-xs text-slate-200"
        >
          {/* Task Title */}
          <div className="space-y-1">
            <label className="block text-slate-300 font-bold">
              Task Title <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              required
              autoFocus
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., Enterprise Multi-Threading & Executive Alignment"
              className="w-full px-3.5 py-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium placeholder-slate-500 focus:outline-none focus:border-violet-500 transition-all text-xs"
            />
          </div>

          {/* Department & job title: context for the AI playbook */}
          <div className="grid grid-cols-2 gap-2.5">
            <div className="space-y-1">
              <label className="block text-slate-300 font-bold">
                Department <span className="text-rose-500">*</span>
              </label>
              {ctx.status === 'ready' && departments.length > 0 ? (
                <select
                  required
                  value={departmentId}
                  onChange={(e) => setDepartmentId(e.target.value)}
                  className="w-full px-2.5 py-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium focus:outline-none focus:border-violet-500 text-xs"
                >
                  <option value="" disabled className="bg-slate-900 text-slate-400">Select department</option>
                  {departments.map((d) => (
                    <option key={d.id} value={d.id} className="bg-slate-900 text-white">{d.label}</option>
                  ))}
                </select>
              ) : (
                <input
                  type="text"
                  required
                  maxLength={160}
                  value={departmentText}
                  onChange={(e) => setDepartmentText(e.target.value)}
                  placeholder={ctx.status === 'loading' ? 'Loading departments…' : 'e.g., Outbound Sales'}
                  className="w-full px-3 py-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium placeholder-slate-500 focus:outline-none focus:border-violet-500 text-xs"
                />
              )}
            </div>
            <div className="space-y-1">
              <label className="block text-slate-300 font-bold">
                Your Job Title <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                required
                maxLength={120}
                value={jobTitle}
                onChange={(e) => setJobTitle(e.target.value)}
                placeholder="e.g., Outbound SDR"
                className="w-full px-3 py-2.5 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium placeholder-slate-500 focus:outline-none focus:border-violet-500 text-xs"
              />
            </div>
          </div>
          <p className="-mt-2 text-[10px] text-slate-400">Used to tailor the AI-generated steps to your role and team.</p>

          {/* Status Selection (Active: purple, In Progress: blue, Completed: emerald) */}
          <div className="space-y-1.5">
            <label className="block text-slate-300 font-bold">Status</label>
            <div className="grid grid-cols-3 gap-2">
              {STATUS_CONFIG.map((opt) => {
                const isSelected = status === opt.id;
                return (
                  <button
                    key={opt.id}
                    type="button"
                    onClick={() => setStatus(opt.id)}
                    className={`py-2 px-3 rounded-xl border text-center transition-all flex items-center justify-center gap-1.5 text-xs font-semibold ${
                      isSelected ? opt.activeClass : opt.inactiveClass
                    }`}
                  >
                    <span
                      className={`w-2 h-2 rounded-full ${isSelected ? 'bg-white' : opt.dotClass}`}
                    />
                    <span>{opt.label}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Date, Time & Estimated Minutes */}
          <div className="grid grid-cols-3 gap-2.5">
            <div className="space-y-1">
              <label className="block text-slate-300 font-bold">Due Date</label>
              <input
                type="date"
                required
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className="w-full px-2.5 py-2 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium focus:outline-none focus:border-violet-500 text-xs"
              />
            </div>

            <div className="space-y-1">
              <label className="block text-slate-300 font-bold">Due Time</label>
              <input
                type="time"
                required
                value={dueTime}
                onChange={(e) => setDueTime(e.target.value)}
                className="w-full px-2.5 py-2 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium focus:outline-none focus:border-violet-500 text-xs"
              />
            </div>

            <div className="space-y-1">
              <label className="block text-slate-300 font-bold">Est. Mins</label>
              <input
                type="number"
                min={5}
                max={480}
                step={5}
                value={estimatedMinutes}
                onChange={(e) => setEstimatedMinutes(Number(e.target.value))}
                className="w-full px-2.5 py-2 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium focus:outline-none focus:border-violet-500 text-xs"
              />
            </div>
          </div>

          {/* Goal & Objective */}
          <div className="space-y-1">
            <label className="block text-slate-300 font-bold">Goal / SOP Objective</label>
            <textarea
              rows={2}
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              placeholder="Provide context, deliverables, or success metrics for this task..."
              className="w-full px-3.5 py-2 rounded-xl bg-slate-900 border border-slate-800 text-white font-medium placeholder-slate-500 focus:outline-none focus:border-violet-500 text-xs resize-none"
            />
          </div>

          {/* Bottom Action Footer */}
          <div className="pt-3 flex items-center justify-end gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-700/80 font-semibold transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={!title.trim() || !(departmentId || departmentText.trim()) || !jobTitle.trim()}
              className="flex items-center gap-1.5 px-5 py-2 rounded-xl bg-violet-600 hover:bg-violet-500 disabled:opacity-50 text-white font-bold shadow-md shadow-violet-900/30 active:scale-95 transition-all"
            >
              <Plus size={14} />
              <span>Create Task</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
