import crypto from 'node:crypto';
import { Router } from 'express';
import multer from 'multer';
import { z } from 'zod';
import { pool, supabaseAdmin } from '../db.js';
import { authJwt } from '../middleware/authJwt.js';
import { can, requirePermission } from '../rbac.js';
import { getActiveMemberId, getDepartmentAccess } from '../departmentAccess.js';

export const bdtActionNodesRouter=Router();
bdtActionNodesRouter.use(authJwt);
const uuid=z.string().uuid(); const createSchema=z.object({parentNodeId:uuid,name:z.string().trim().min(1).max(160),purpose:z.string().trim().max(2000).nullable().optional()});
const updateSchema=z.object({name:z.string().trim().min(1).max(160).optional(),purpose:z.string().trim().max(2000).nullable().optional(),parentNodeId:uuid.optional()});
const linkSchema=z.object({label:z.string().trim().min(1).max(255),url:z.string().trim().url().max(2048)});
const allowedExtensions=new Set(['pdf','doc','docx','xls','xlsx','ppt','pptx','csv','txt','md','json','png','jpg','jpeg','webp','gif','zip']);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024},fileFilter:(_req,file,cb)=>{const ext=file.originalname.split('.').pop()?.toLowerCase()??'';const ok=allowedExtensions.has(ext);if(!ok)return cb(new Error('file_type_not_allowed'));return cb(null,true);}});
function nameOf(file:string){return file.replace(/[\r\n"\\]/g,'_').slice(0,255)||'download';}
async function manager(req:any,department:string){const {companyId,role,userId}=req.auth;if(!companyId||!role||!userId||!can(role,companyId,'twin','write'))return false;return (await getDepartmentAccess({companyId,role,userId},department)).manage;}
async function member(company:string,user:string){return getActiveMemberId(company,user);}
async function actionNode(company:string,id:string){const {rows}=await pool.query<any>(`select n.*,p.metadata parent_metadata,p.department_id parent_department_id,p.label parent_label from public.department_bdt_nodes n join public.department_bdt_nodes p on p.id=n.parent_node_id and p.company_id=n.company_id where n.company_id=$1 and n.id=$2 and n.node_type='action' and n.parent_node_id is not null and n.metadata->>'workspaceKind' is null and p.metadata->>'workspaceKind' is not null`,[company,id]);return rows[0]??null;}
async function readable(req:any,node:any){return Boolean(node&&(await getDepartmentAccess(req.auth,node.department_id)).read);}
async function contents(company:string,id:string){const [tasks,resources]=await Promise.all([pool.query(`select count(*)::int count from public.bdt_tasks where company_id=$1 and node_id=$2`,[company,id]),pool.query(`select count(*)::int count from public.bdt_action_resources where company_id=$1 and node_id=$2`,[company,id])]);return Number(tasks.rows[0].count)+Number(resources.rows[0].count);}
async function resourceCount(company:string,id:string){const {rows}=await pool.query<any>(`select count(*)::int count from public.bdt_action_resources where company_id=$1 and node_id=$2`,[company,id]);return Number(rows[0].count);}
function nodeShape(r:any){return{id:r.id,departmentId:r.department_id,parentNodeId:r.parent_node_id,name:r.label,purpose:r.metadata?.purpose??null,nodeType:r.node_type,nodeLevel:r.node_level,parentLabel:r.parent_label};}
function error(res:any,e:any){if(e instanceof z.ZodError)return res.status(400).json({error:'invalid_request',details:e.flatten()});if(e?.code==='23505')return res.status(409).json({error:'duplicate_resource'});console.error('[bdt-action-nodes]',e);return res.status(500).json({error:'bdt_action_node_failed'});}

bdtActionNodesRouter.post('/',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=createSchema.parse(req.body);const {rows}=await pool.query<any>(`select id,department_id,label,metadata from public.department_bdt_nodes where company_id=$1 and id=$2 and metadata->>'workspaceKind' is not null`,[c,input.parentNodeId]);const parent=rows[0];if(!parent)return res.status(404).json({error:'workspace_parent_not_found'});if(!await manager(req,parent.department_id))return res.status(403).json({error:'department_forbidden'});const {rows:created}=await pool.query<any>(`insert into public.department_bdt_nodes(company_id,department_id,parent_node_id,label,node_type,node_level,score,sort_order,metadata) values($1,$2,$3,$4,'action','action',75,coalesce((select max(sort_order)+1 from public.department_bdt_nodes where company_id=$1 and parent_node_id=$3),0),$5::jsonb) returning id`,[c,parent.department_id,parent.id,input.name,JSON.stringify(input.purpose?{purpose:input.purpose}:{})]);res.status(201).json(nodeShape(await actionNode(c,created[0].id)));}catch(e){error(res,e);}});
bdtActionNodesRouter.patch('/:id',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=updateSchema.parse(req.body),n=await actionNode(c,req.params.id);if(!n)return res.status(404).json({error:'action_node_not_found'});if(!await manager(req,n.department_id))return res.status(403).json({error:'department_forbidden'});if(await contents(c,n.id))return res.status(409).json({error:'action_node_locked'});let parent=n;if(input.parentNodeId){const {rows}=await pool.query<any>(`select id,department_id,metadata from public.department_bdt_nodes where company_id=$1 and id=$2 and metadata->>'workspaceKind' is not null`,[c,input.parentNodeId]);parent=rows[0];if(!parent||parent.department_id!==n.department_id)return res.status(409).json({error:'invalid_workspace_parent'});}const metadata={...(n.metadata??{})};if(input.purpose!==undefined){if(input.purpose)metadata.purpose=input.purpose;else delete metadata.purpose;}await pool.query(`update public.department_bdt_nodes set label=$3,parent_node_id=$4,metadata=$5::jsonb,updated_at=now() where company_id=$1 and id=$2`,[c,n.id,input.name??n.label,parent.id,JSON.stringify(metadata)]);res.json(nodeShape(await actionNode(c,n.id)));}catch(e){error(res,e);}});
bdtActionNodesRouter.delete('/:id',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId,n=await actionNode(c,req.params.id);if(!n)return res.status(404).json({error:'action_node_not_found'});if(!await manager(req,n.department_id))return res.status(403).json({error:'department_forbidden'});if(await contents(c,n.id))return res.status(409).json({error:'action_node_not_empty'});await pool.query(`delete from public.department_bdt_nodes where company_id=$1 and id=$2`,[c,n.id]);res.status(204).send();});

bdtActionNodesRouter.get('/:nodeId/resources',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,n=await actionNode(c,req.params.nodeId);if(!await readable(req,n))return res.status(404).json({error:'action_node_not_found'});const {rows}=await pool.query<any>(`select id,kind,label,original_name,mime_type,byte_size,external_url,created_at from public.bdt_action_resources where company_id=$1 and node_id=$2 order by created_at asc`,[c,n.id]);res.json({items:rows});});
bdtActionNodesRouter.post('/:nodeId/resources/links',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=linkSchema.parse(req.body),url=new URL(input.url);if(url.protocol!=='https:')return res.status(400).json({error:'https_required'});const n=await actionNode(c,req.params.nodeId);if(!await readable(req,n))return res.status(404).json({error:'action_node_not_found'});if(await resourceCount(c,n.id)>=20)return res.status(409).json({error:'resource_limit_reached'});const by=await member(c,req.auth.userId);const {rows}=await pool.query<any>(`insert into public.bdt_action_resources(company_id,department_id,node_id,kind,label,external_url,created_by_member_id) values($1,$2,$3,'link',$4,$5,$6) returning id,kind,label,external_url,created_at`,[c,n.department_id,n.id,input.label,url.toString(),by]);res.status(201).json(rows[0]);}catch(e){error(res,e);}});
bdtActionNodesRouter.post('/:nodeId/resources/files',requirePermission('twin','read'),upload.single('file'),async(req:any,res)=>{const c=req.auth.companyId;try{const n=await actionNode(c,req.params.nodeId);if(!await readable(req,n))return res.status(404).json({error:'action_node_not_found'});if(!req.file)return res.status(400).json({error:'file_required'});if(await resourceCount(c,n.id)>=20)return res.status(409).json({error:'resource_limit_reached'});const checksum=crypto.createHash('sha256').update(req.file.buffer).digest('hex'),ext=req.file.originalname.split('.').pop()?.toLowerCase()||'bin',path=`${c}/${n.id}/${crypto.randomUUID()}.${ext}`;const {error:up}=await supabaseAdmin.storage.from('bdt-action-resources').upload(path,req.file.buffer,{contentType:req.file.mimetype,upsert:false});if(up)return res.status(500).json({error:'resource_storage_upload_failed'});try{const by=await member(c,req.auth.userId);const {rows}=await pool.query<any>(`insert into public.bdt_action_resources(company_id,department_id,node_id,kind,label,storage_path,original_name,mime_type,byte_size,checksum,created_by_member_id) values($1,$2,$3,'file',$4,$5,$6,$7,$8,$9,$10) returning id,kind,label,original_name,mime_type,byte_size,created_at`,[c,n.department_id,n.id,nameOf(req.file.originalname),path,nameOf(req.file.originalname),req.file.mimetype,req.file.size,checksum,by]);res.status(201).json(rows[0]);}catch(e){await supabaseAdmin.storage.from('bdt-action-resources').remove([path]);throw e;}}catch(e){error(res,e);}});
bdtActionNodesRouter.get('/:nodeId/resources/:resourceId/download',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,n=await actionNode(c,req.params.nodeId);if(!await readable(req,n))return res.status(404).json({error:'action_node_not_found'});const {rows}=await pool.query<any>(`select storage_path,original_name,mime_type from public.bdt_action_resources where company_id=$1 and node_id=$2 and id=$3 and kind='file'`,[c,n.id,req.params.resourceId]);const r=rows[0];if(!r)return res.status(404).json({error:'resource_not_found'});const {data,error:downloadError}=await supabaseAdmin.storage.from('bdt-action-resources').download(r.storage_path);if(downloadError||!data)return res.status(500).json({error:'resource_download_failed'});res.setHeader('Content-Type',r.mime_type);res.setHeader('Content-Disposition',`attachment; filename="${nameOf(r.original_name)}"`);res.send(Buffer.from(await data.arrayBuffer()));});
bdtActionNodesRouter.delete('/:nodeId/resources/:resourceId',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,n=await actionNode(c,req.params.nodeId);if(!await readable(req,n))return res.status(404).json({error:'action_node_not_found'});const {rows}=await pool.query<any>(`select storage_path from public.bdt_action_resources where company_id=$1 and node_id=$2 and id=$3`,[c,n.id,req.params.resourceId]);const r=rows[0];if(!r)return res.status(404).json({error:'resource_not_found'});if(r.storage_path){const {error:remove}=await supabaseAdmin.storage.from('bdt-action-resources').remove([r.storage_path]);if(remove)return res.status(500).json({error:'resource_storage_remove_failed'});}await pool.query(`delete from public.bdt_action_resources where company_id=$1 and id=$2`,[c,req.params.resourceId]);res.status(204).send();});
