import { Router } from 'express';
import { z } from 'zod';
import { pool } from '../db.js';
import { authJwt } from '../middleware/authJwt.js';
import { can, requirePermission } from '../rbac.js';
import { getActiveMemberId, getDepartmentAccess } from '../departmentAccess.js';

export const bdtFormNodesRouter = Router();
bdtFormNodesRouter.use(authJwt);
const uuid = z.string().uuid();
const fieldTypes = ['short_text','long_text','number','date','checkbox','single_select','url','email'] as const;
const fieldSchema = z.object({ label:z.string().trim().min(1).max(160), fieldType:z.enum(fieldTypes), required:z.boolean().default(false), options:z.array(z.string().trim().min(1).max(160)).min(1).max(50).optional() }).superRefine((v,ctx)=>{ if(v.fieldType==='single_select'&&!v.options)ctx.addIssue({code:'custom',message:'Select options are required'}); if(v.fieldType!=='single_select'&&v.options)ctx.addIssue({code:'custom',message:'Options are only valid for single select'}); if(v.options&&new Set(v.options.map(x=>x.toLowerCase())).size!==v.options.length)ctx.addIssue({code:'custom',message:'Options must be unique'}); });
const createSchema=z.object({parentNodeId:uuid,name:z.string().trim().min(1).max(160),purpose:z.string().trim().max(2000).nullable().optional(),fields:z.array(fieldSchema).min(1).max(30)});
const patchSchema=z.object({name:z.string().trim().min(1).max(160).optional(),purpose:z.string().trim().max(2000).nullable().optional(),parentNodeId:uuid.optional()});
const schemaSchema=z.object({fields:z.array(fieldSchema).min(1).max(30)});
const valuesSchema=z.object({values:z.record(z.string().uuid(),z.unknown())});
const schemaRoles=new Set(['super_admin','founder','co_founder','admin']);

async function activeMember(companyId:string,userId:string){ return getActiveMemberId(companyId,userId); }
async function readable(req:any,departmentId:string){ return Boolean((await activeMember(req.auth.companyId,req.auth.userId)) && (await getDepartmentAccess(req.auth,departmentId)).read); }
async function schemaAdmin(req:any,departmentId:string){ const a=req.auth; return Boolean(a.companyId&&a.userId&&schemaRoles.has(a.role)&&can(a.role,a.companyId,'twin','write')&&await activeMember(a.companyId,a.userId)&&await readable(req,departmentId)); }
async function manager(req:any,departmentId:string){ const a=req.auth; return Boolean(a.companyId&&a.userId&&can(a.role,a.companyId,'twin','write')&&(await getDepartmentAccess(a,departmentId)).manage); }
async function parent(companyId:string,id:string){ const {rows}=await pool.query<any>(`select id,company_id,department_id,label,metadata from public.department_bdt_nodes where company_id=$1 and id=$2 and metadata->>'workspaceKind' is not null`,[companyId,id]); return rows[0]??null; }
async function form(companyId:string,id:string){ const {rows}=await pool.query<any>(`select n.id,n.company_id,n.department_id,n.parent_node_id,n.label,n.metadata,f.schema_locked_at,f.next_record_number,f.created_at,f.updated_at,p.label parent_label from public.bdt_form_nodes f join public.department_bdt_nodes n on n.company_id=f.company_id and n.id=f.node_id join public.department_bdt_nodes p on p.company_id=f.company_id and p.id=f.parent_node_id where f.company_id=$1 and f.node_id=$2 and n.node_type='resource' and n.node_level='form' and n.metadata->>'workspaceKind' is null and p.metadata->>'workspaceKind' is not null`,[companyId,id]); return rows[0]??null; }
async function fields(companyId:string,nodeId:string){ const {rows}=await pool.query<any>(`select id,label,field_type,required,position,options from public.bdt_form_fields where company_id=$1 and form_node_id=$2 order by position asc`,[companyId,nodeId]); return rows.map(r=>({id:r.id,label:r.label,fieldType:r.field_type,required:r.required,position:r.position,options:r.options??undefined})); }
async function recordCount(companyId:string,nodeId:string){ const {rows}=await pool.query<any>(`select count(*)::int count from public.bdt_form_records where company_id=$1 and form_node_id=$2`,[companyId,nodeId]); return Number(rows[0].count); }
async function shape(req:any,n:any){ const member=await activeMember(req.auth.companyId,req.auth.userId); return {id:n.id,departmentId:n.department_id,parentNodeId:n.parent_node_id,name:n.label,purpose:n.metadata?.purpose??null,parentLabel:n.parent_label,schemaLockedAt:n.schema_locked_at,recordCount:await recordCount(req.auth.companyId,n.id),fields:await fields(req.auth.companyId,n.id),canManageSchema:await schemaAdmin(req,n.department_id),canDeleteRecords:await manager(req,n.department_id),memberId:member}; }
async function validateValues(companyId:string,nodeId:string,values:any){ if(!values||typeof values!=='object'||Array.isArray(values))throw new Error('invalid_values'); const fs=await fields(companyId,nodeId); const known=new Map(fs.map(f=>[f.id,f])); for(const key of Object.keys(values))if(!known.has(key))throw new Error('unknown_field'); for(const f of fs){ const present=Object.prototype.hasOwnProperty.call(values,f.id),v=values[f.id]; if(f.required&&!present)throw new Error('required_field'); if(!present)continue; if(v===null){ if(f.required)throw new Error('required_field'); continue; } const s=typeof v==='string'; if(f.fieldType==='short_text'&&(!s||v.length>500))throw new Error('invalid_value'); if(f.fieldType==='long_text'&&(!s||v.length>20000))throw new Error('invalid_value'); if(f.fieldType==='number'&&(typeof v!=='number'||!Number.isFinite(v)))throw new Error('invalid_value'); if(f.fieldType==='checkbox'&&typeof v!=='boolean')throw new Error('invalid_value'); if(f.fieldType==='date'&&(!s||!/^\\d{4}-\\d{2}-\\d{2}$/.test(v)||Number.isNaN(Date.parse(`${v}T00:00:00Z`))))throw new Error('invalid_value'); if(f.fieldType==='url'&&(!s||v.length>2048||(()=>{try{return new URL(v).protocol==='https:';}catch{return false;}})()===false))throw new Error('invalid_value'); if(f.fieldType==='email'&&(!s||v.length>320||!z.string().email().safeParse(v).success))throw new Error('invalid_value'); if(f.fieldType==='single_select'&&(!s||!f.options?.includes(v)))throw new Error('invalid_value'); if(f.required&&['short_text','long_text','date','url','email','single_select'].includes(f.fieldType)&&(!s||!v.trim()))throw new Error('required_field'); } }
function fail(res:any,e:any){ if(e instanceof z.ZodError)return res.status(400).json({error:'invalid_request',details:e.flatten()}); if(['invalid_values','unknown_field','invalid_value','required_field'].includes(e?.message))return res.status(400).json({error:e.message}); if(e?.code==='23505')return res.status(400).json({error:'duplicate_field_label_or_position'}); if(e?.code==='23503')return res.status(409).json({error:'invalid_reference'}); console.error('[bdt-form-nodes]',e); return res.status(500).json({error:'bdt_form_node_failed'}); }

bdtFormNodesRouter.get('/',requirePermission('twin','read'),async(req:any,res)=>{ const c=req.auth.companyId; const params:any=[c]; let where='f.company_id=$1'; if(req.query.departmentId){params.push(String(req.query.departmentId));where+=' and f.department_id=$2';} const {rows}=await pool.query<any>(`select f.node_id from public.bdt_form_nodes f where ${where} order by f.created_at desc`,params); const items=[]; for(const r of rows){const n=await form(c,r.node_id);if(n&&await readable(req,n.department_id))items.push(await shape(req,n));} res.json({items}); });
bdtFormNodesRouter.post('/',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=createSchema.parse(req.body),p=await parent(c,input.parentNodeId);if(!p)return res.status(404).json({error:'workspace_parent_not_found'});if(!await schemaAdmin(req,p.department_id))return res.status(403).json({error:'schema_admin_required'});const by=await activeMember(c,req.auth.userId),client=await pool.connect();try{await client.query('begin');const {rows}=await client.query<any>(`insert into public.department_bdt_nodes(company_id,department_id,parent_node_id,label,node_type,node_level,score,sort_order,metadata) values($1,$2,$3,$4,'resource','form',75,coalesce((select max(sort_order)+1 from public.department_bdt_nodes where company_id=$1 and parent_node_id=$3),0),$5::jsonb) returning id`,[c,p.department_id,p.id,input.name,JSON.stringify(input.purpose?{purpose:input.purpose}:{})]);const id=rows[0].id;await client.query(`insert into public.bdt_form_nodes(node_id,company_id,department_id,parent_node_id,created_by_member_id) values($1,$2,$3,$4,$5)`,[id,c,p.department_id,p.id,by]);for(const [i,f] of input.fields.entries())await client.query(`insert into public.bdt_form_fields(company_id,department_id,form_node_id,label,field_type,required,position,options) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[c,p.department_id,id,f.label,f.fieldType,f.required,i,f.options?JSON.stringify(f.options):null]);await client.query('commit');res.status(201).json(await shape(req,await form(c,id)));}catch(e){await client.query('rollback');throw e;}finally{client.release();}}catch(e){fail(res,e);}});
bdtFormNodesRouter.get('/:id',requirePermission('twin','read'),async(req:any,res)=>{const n=await form(req.auth.companyId,req.params.id);if(!n||!await readable(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});res.json(await shape(req,n));});
bdtFormNodesRouter.patch('/:id',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=patchSchema.parse(req.body),n=await form(c,req.params.id);if(!n)return res.status(404).json({error:'form_node_not_found'});if(!await schemaAdmin(req,n.department_id))return res.status(403).json({error:'schema_admin_required'});let p=n;if(input.parentNodeId){if(await recordCount(c,n.id))return res.status(409).json({error:'form_node_populated'});p=await parent(c,input.parentNodeId);if(!p||p.department_id!==n.department_id)return res.status(409).json({error:'invalid_workspace_parent'});}const metadata={...(n.metadata??{})};if(input.purpose!==undefined){if(input.purpose)metadata.purpose=input.purpose;else delete metadata.purpose;}await pool.query(`update public.department_bdt_nodes set label=$3,parent_node_id=$4,metadata=$5::jsonb,updated_at=now() where company_id=$1 and id=$2`,[c,n.id,input.name??n.label,p.id,JSON.stringify(metadata)]);await pool.query(`update public.bdt_form_nodes set parent_node_id=$3 where company_id=$1 and node_id=$2`,[c,n.id,p.id]);res.json(await shape(req,await form(c,n.id)));}catch(e){fail(res,e);}});
bdtFormNodesRouter.put('/:id/schema',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=schemaSchema.parse(req.body),n=await form(c,req.params.id);if(!n)return res.status(404).json({error:'form_node_not_found'});if(!await schemaAdmin(req,n.department_id))return res.status(403).json({error:'schema_admin_required'});if(n.schema_locked_at)return res.status(409).json({error:'schema_locked'});const client=await pool.connect();try{await client.query('begin');await client.query(`delete from public.bdt_form_fields where company_id=$1 and form_node_id=$2`,[c,n.id]);for(const [i,f] of input.fields.entries())await client.query(`insert into public.bdt_form_fields(company_id,department_id,form_node_id,label,field_type,required,position,options) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[c,n.department_id,n.id,f.label,f.fieldType,f.required,i,f.options?JSON.stringify(f.options):null]);await client.query('commit');res.json(await shape(req,await form(c,n.id)));}catch(e){await client.query('rollback');throw e;}finally{client.release();}}catch(e){fail(res,e);}});
bdtFormNodesRouter.delete('/:id',requirePermission('twin','write'),async(req:any,res)=>{const c=req.auth.companyId,n=await form(c,req.params.id);if(!n||!await schemaAdmin(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});if(await recordCount(c,n.id))return res.status(409).json({error:'form_node_populated'});await pool.query(`delete from public.department_bdt_nodes where company_id=$1 and id=$2`,[c,n.id]);res.status(204).send();});
bdtFormNodesRouter.get('/:id/records',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,n=await form(c,req.params.id);if(!n||!await readable(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});const limit=Math.min(Math.max(Number(req.query.limit)||25,1),100),offset=Math.max(Number(req.query.offset)||0,0);const {rows}=await pool.query<any>(`select id,record_number,values,created_at,updated_at from public.bdt_form_records where company_id=$1 and form_node_id=$2 order by record_number desc limit $3 offset $4`,[c,n.id,limit,offset]);res.json({items:rows.map(r=>({id:r.id,recordNumber:Number(r.record_number),values:r.values,createdAt:r.created_at,updatedAt:r.updated_at})),total:await recordCount(c,n.id)});});
bdtFormNodesRouter.post('/:id/records',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=valuesSchema.parse(req.body),n=await form(c,req.params.id);if(!n||!await readable(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});await validateValues(c,n.id,input.values);const by=await activeMember(c,req.auth.userId),client=await pool.connect();try{await client.query('begin');const locked=(await client.query<any>(`select next_record_number from public.bdt_form_nodes where company_id=$1 and node_id=$2 for update`,[c,n.id])).rows[0];const number=Number(locked.next_record_number);await client.query(`update public.bdt_form_nodes set next_record_number=$3,schema_locked_at=coalesce(schema_locked_at,now()) where company_id=$1 and node_id=$2`,[c,n.id,number+1]);const {rows}=await client.query<any>(`insert into public.bdt_form_records(company_id,department_id,form_node_id,record_number,values,created_by_member_id,updated_by_member_id) values($1,$2,$3,$4,$5::jsonb,$6,$6) returning id,record_number,values,created_at,updated_at`,[c,n.department_id,n.id,number,JSON.stringify(input.values),by]);await client.query('commit');const r=rows[0];res.status(201).json({id:r.id,recordNumber:Number(r.record_number),values:r.values,createdAt:r.created_at,updatedAt:r.updated_at});}catch(e){await client.query('rollback');throw e;}finally{client.release();}}catch(e){fail(res,e);}});
bdtFormNodesRouter.get('/:id/records/:recordId',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,n=await form(c,req.params.id);if(!n||!await readable(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});const {rows}=await pool.query<any>(`select id,record_number,values,created_at,updated_at from public.bdt_form_records where company_id=$1 and form_node_id=$2 and id=$3`,[c,n.id,req.params.recordId]);if(!rows[0])return res.status(404).json({error:'record_not_found'});const r=rows[0];res.json({id:r.id,recordNumber:Number(r.record_number),values:r.values,createdAt:r.created_at,updatedAt:r.updated_at});});
bdtFormNodesRouter.patch('/:id/records/:recordId',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=valuesSchema.parse(req.body),n=await form(c,req.params.id);if(!n||!await readable(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});await validateValues(c,n.id,input.values);const by=await activeMember(c,req.auth.userId);const {rows}=await pool.query<any>(`update public.bdt_form_records set values=$4::jsonb,updated_by_member_id=$5,updated_at=now() where company_id=$1 and form_node_id=$2 and id=$3 returning id,record_number,values,created_at,updated_at`,[c,n.id,req.params.recordId,JSON.stringify(input.values),by]);if(!rows[0])return res.status(404).json({error:'record_not_found'});const r=rows[0];res.json({id:r.id,recordNumber:Number(r.record_number),values:r.values,createdAt:r.created_at,updatedAt:r.updated_at});}catch(e){fail(res,e);}});
bdtFormNodesRouter.delete('/:id/records/:recordId',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,n=await form(c,req.params.id);if(!n||!await manager(req,n.department_id))return res.status(404).json({error:'form_node_not_found'});const result=await pool.query(`delete from public.bdt_form_records where company_id=$1 and form_node_id=$2 and id=$3`,[c,n.id,req.params.recordId]);if(!result.rowCount)return res.status(404).json({error:'record_not_found'});res.status(204).send();});
