import { Router } from 'express';
import { z } from 'zod';
import { pool } from '../db.js';
import { authJwt } from '../middleware/authJwt.js';
import { can, requirePermission, type RoleId } from '../rbac.js';
import { getActiveMemberId, getDepartmentAccess } from '../departmentAccess.js';

export const bdtTasksRouter = Router();
bdtTasksRouter.use(authJwt);
const uuid=z.string().uuid();
const relatedSchema=z.discriminatedUnion('type',[...['product','account','lead','deal','quote','order','invoice'].map(type=>z.object({type:z.literal(type as any),id:uuid}))] as any);
const taskSchema=z.object({nodeId:uuid,assigneeMemberId:uuid,title:z.string().trim().min(1).max(160),instructions:z.string().trim().max(4000).nullable().optional(),dueOn:z.string().date().nullable().optional(),priority:z.enum(['low','normal','high']).default('normal'),related:relatedSchema.nullable().optional()});
const updateSchema=taskSchema.omit({nodeId:true,assigneeMemberId:true,title:true}).extend({title:z.string().trim().min(1).max(160).optional(),assigneeMemberId:uuid.optional()});
const progressSchema=z.object({status:z.enum(['todo','in_progress','blocked','done']),workNote:z.string().trim().max(4000).nullable().optional(),blockedReason:z.string().trim().max(1000).nullable().optional()});
const cancelSchema=z.object({reason:z.string().trim().min(1).max(1000)});
const capabilityRecords:Record<string,string[]>={prod_product_catalogue:['product'],prod_pricing_management:['product'],prod_inventory_readiness:['product'],sales_customers_contacts:['account'],sales_lead_management:['lead'],sales_deal_management:['deal'],sales_quotations:['quote'],sales_orders_invoices:['order','invoice'],sales_collections:['invoice']};
const relationTable:Record<string,{table:string;label:string}>={product:{table:'catalog_products',label:"coalesce(code || ' · ', '') || name"},account:{table:'crm_accounts',label:'name'},lead:{table:'crm_leads',label:'name'},deal:{table:'crm_deals',label:'name'},quote:{table:'sales_quotes',label:'document_number'},order:{table:'sales_orders',label:'document_number'},invoice:{table:'sales_invoices',label:'document_number'}};

async function nodeFor(companyId:string,nodeId:string){const {rows}=await pool.query<any>(`select n.id,n.department_id,n.parent_node_id,n.node_type,n.metadata,n.metadata->>'sourceKey' source_key,p.metadata->>'sourceKey' parent_source_key from public.department_bdt_nodes n left join public.department_bdt_nodes p on p.id=n.parent_node_id and p.company_id=n.company_id where n.company_id=$1 and n.id=$2`,[companyId,nodeId]);const node=rows[0];if(!node)return null;const workspace=Boolean(node.metadata?.workspaceKind);const action=node.node_type==='action'&&!node.metadata?.workspaceKind&&Boolean(node.parent_node_id)&&Boolean(rows[0].parent_source_key!==undefined||rows[0].parent_node_id);const parentWorkspace=action ? (await pool.query<any>(`select metadata from public.department_bdt_nodes where company_id=$1 and id=$2`,[companyId,node.parent_node_id])).rows[0]?.metadata?.workspaceKind : null;if(!workspace&&!(action&&parentWorkspace))return null;return {...node,is_action:action,parent_workspace_kind:parentWorkspace};}
async function actorMember(company:string,user:string){return getActiveMemberId(company,user);}
async function canManage(req:any,department:string){const {companyId,role,userId}=req.auth;if(!companyId||!role||!userId||!can(role,companyId,'twin','write'))return false;return (await getDepartmentAccess({companyId,role,userId},department)).manage;}
async function eligible(company:string,department:string,member:string){const {rows}=await pool.query<{user_id:string;role:RoleId}>(`select user_id,role from public.company_members where company_id=$1 and id=$2 and status='active'`,[company,member]);const m=rows[0];return Boolean(m&&can(m.role,company,'twin','read')&&(await getDepartmentAccess({companyId:company,userId:m.user_id,role:m.role},department)).read);}
function allowedTypes(node:any){return capabilityRecords[node.source_key]??capabilityRecords[node.parent_source_key]??[];}
async function relation(company:string,input:any){const empty={product_id:null,account_id:null,lead_id:null,deal_id:null,quote_id:null,order_id:null,invoice_id:null};if(!input)return{type:null,label:null,columns:empty};const target=relationTable[input.type];const {rows}=await pool.query<any>(`select ${target.label} label from public.${target.table} where company_id=$1 and id=$2`,[company,input.id]);if(!rows[0])throw new Error('related_record_not_found');return{type:input.type,label:rows[0].label,columns:{...empty,[`${input.type}_id`]:input.id}};}
async function row(company:string,id:string){const {rows}=await pool.query<any>(`select t.*,n.label node_label,n.parent_node_id,d.label department_label,a.first_name assignee_first_name,a.last_name assignee_last_name,b.first_name assigner_first_name,b.last_name assigner_last_name from public.bdt_tasks t join public.department_bdt_nodes n on n.company_id=t.company_id and n.id=t.node_id join public.departments d on d.company_id=t.company_id and d.id=t.department_id left join public.company_members am on am.company_id=t.company_id and am.id=t.assignee_member_id left join public.user_profiles a on a.id=am.user_id left join public.company_members bm on bm.company_id=t.company_id and bm.id=t.assigned_by_member_id left join public.user_profiles b on b.id=bm.user_id where t.company_id=$1 and t.id=$2`,[company,id]);return rows[0]??null;}
function shape(r:any,manager:boolean,member:string|null){const types=['product','account','lead','deal','quote','order','invoice'];const type=types.find(x=>r[`${x}_id`]);return {...r,related:r.related_record_type?{type:r.related_record_type,id:type?r[`${type}_id`]:null,label:r.related_record_label,available:Boolean(type&&r[`${type}_id`])}:null,overdue:Boolean(r.due_on&&!['done','cancelled'].includes(r.status)&&r.due_on<new Date().toISOString().slice(0,10)),canManage:manager,canProgress:manager||r.assignee_member_id===member};}
function fail(res:any,e:any){if(e instanceof z.ZodError)return res.status(400).json({error:'invalid_request',details:e.flatten()});if(e?.message==='related_record_not_found')return res.status(409).json({error:'invalid_related_record'});if(e?.code==='23503')return res.status(409).json({error:'invalid_reference'});console.error('[bdt-tasks]',e);return res.status(500).json({error:'bdt_task_failed'});}

bdtTasksRouter.get('/mine',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,m=await actorMember(c,req.auth.userId);if(!c||!m)return res.status(403).json({error:'no_member'});const {rows}=await pool.query<any>(`select id from public.bdt_tasks where company_id=$1 and assignee_member_id=$2 order by case when status in ('done','cancelled') then 1 else 0 end,case when due_on<current_date and status not in ('done','cancelled') then 0 else 1 end,due_on asc nulls last,created_at desc`,[c,m]);const items=(await Promise.all(rows.map(x=>row(c,x.id)))).filter(Boolean).map(x=>shape(x,false,m));res.json({items,total:items.length,counts:{active:items.filter(x=>!['done','cancelled'].includes(x.status)).length,blocked:items.filter(x=>x.status==='blocked').length,overdue:items.filter(x=>x.overdue).length,completed:items.filter(x=>x.status==='done').length,cancelled:items.filter(x=>x.status==='cancelled').length}});});
bdtTasksRouter.get('/assignees',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,node=await nodeFor(c,String(req.query.nodeId||''));if(!node||!(await canManage(req,node.department_id)))return res.status(404).json({error:'node_not_found'});const {rows}=await pool.query<any>(`select cm.id,cm.user_id,cm.role,up.first_name,up.last_name,up.title,up.avatar_url from public.company_members cm left join public.user_profiles up on up.id=cm.user_id where cm.company_id=$1 and cm.status='active' order by up.first_name nulls last`,[c]);const items=[];for(const x of rows)if(await eligible(c,node.department_id,x.id))items.push(x);res.json({items});});
bdtTasksRouter.get('/',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,node=await nodeFor(c,String(req.query.nodeId||''));if(!node)return res.status(404).json({error:'node_not_found'});const access=await getDepartmentAccess(req.auth,node.department_id);if(!access.read)return res.status(404).json({error:'node_not_found'});const m=await actorMember(c,req.auth.userId),manager=await canManage(req,node.department_id);const {rows}=await pool.query<any>(`select id from public.bdt_tasks where company_id=$1 and node_id=$2 order by created_at desc`,[c,node.id]);const items=(await Promise.all(rows.map(x=>row(c,x.id)))).filter(Boolean).map(x=>shape(x,manager,m));res.json({items,total:items.length,counts:{}});});
bdtTasksRouter.post('/',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=taskSchema.parse(req.body),node=await nodeFor(c,input.nodeId);if(!node)return res.status(404).json({error:'node_not_found'});if(!(await canManage(req,node.department_id)))return res.status(403).json({error:'department_forbidden'});if(!await eligible(c,node.department_id,input.assigneeMemberId))return res.status(409).json({error:'ineligible_assignee'});if(input.related&&!allowedTypes(node).includes(input.related.type))return res.status(409).json({error:'incompatible_related_record'});const rel=await relation(c,input.related),by=await actorMember(c,req.auth.userId);const {rows}=await pool.query<any>(`insert into public.bdt_tasks(company_id,department_id,node_id,title,instructions,due_on,priority,assignee_member_id,assigned_by_member_id,related_record_type,related_record_label,product_id,account_id,lead_id,deal_id,quote_id,order_id,invoice_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) returning id`,[c,node.department_id,node.id,input.title,input.instructions??null,input.dueOn??null,input.priority,input.assigneeMemberId,by,rel.type,rel.label,rel.columns.product_id,rel.columns.account_id,rel.columns.lead_id,rel.columns.deal_id,rel.columns.quote_id,rel.columns.order_id,rel.columns.invoice_id]);res.status(201).json(shape(await row(c,rows[0].id),true,by));}catch(e){fail(res,e);}});
bdtTasksRouter.get('/:id',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,r=await row(c,req.params.id);if(!r)return res.status(404).json({error:'task_not_found'});const a=await getDepartmentAccess(req.auth,r.department_id);if(!a.read)return res.status(404).json({error:'task_not_found'});res.json(shape(r,await canManage(req,r.department_id),await actorMember(c,req.auth.userId)));});
bdtTasksRouter.patch('/:id',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=updateSchema.parse(req.body),r=await row(c,req.params.id);if(!r)return res.status(404).json({error:'task_not_found'});if(!(await canManage(req,r.department_id)))return res.status(403).json({error:'department_forbidden'});if(['done','cancelled'].includes(r.status))return res.status(409).json({error:'task_terminal'});const node=await nodeFor(c,r.node_id);if(input.assigneeMemberId&&!await eligible(c,r.department_id,input.assigneeMemberId))return res.status(409).json({error:'ineligible_assignee'});if(input.related&&!allowedTypes(node).includes(input.related.type))return res.status(409).json({error:'incompatible_related_record'});const rel=input.related===undefined?null:await relation(c,input.related),values:any[]=[c,r.id],fields:string[]=[];const set=(k:string,v:any)=>{values.push(v);fields.push(`${k}=$${values.length}`)};if(input.title!==undefined)set('title',input.title);if(input.instructions!==undefined)set('instructions',input.instructions);if(input.dueOn!==undefined)set('due_on',input.dueOn);if(input.priority!==undefined)set('priority',input.priority);if(input.assigneeMemberId!==undefined)set('assignee_member_id',input.assigneeMemberId);if(rel){set('related_record_type',rel.type);set('related_record_label',rel.label);Object.entries(rel.columns).forEach(([k,v])=>set(k,v));}if(fields.length)await pool.query(`update public.bdt_tasks set ${fields.join(',')},updated_at=now() where company_id=$1 and id=$2`,values);const m=await actorMember(c,req.auth.userId);res.json(shape(await row(c,r.id),true,m));}catch(e){fail(res,e);}});
bdtTasksRouter.patch('/:id/progress',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=progressSchema.parse(req.body),r=await row(c,req.params.id);if(!r)return res.status(404).json({error:'task_not_found'});const m=await actorMember(c,req.auth.userId),manager=await canManage(req,r.department_id);if(!manager&&r.assignee_member_id!==m)return res.status(404).json({error:'task_not_found'});if(r.status==='cancelled')return res.status(409).json({error:'task_cancelled'});if(input.status==='blocked'&&!input.blockedReason)return res.status(409).json({error:'blocked_reason_required'});if(input.status==='done'&&!input.workNote?.trim())return res.status(409).json({error:'completion_note_required'});await pool.query(`update public.bdt_tasks set status=$3,work_note=$4,blocked_reason=$5,completed_at=$6,updated_at=now() where company_id=$1 and id=$2`,[c,r.id,input.status,input.workNote??r.work_note??null,input.status==='blocked'?input.blockedReason:null,input.status==='done'?new Date():null]);res.json(shape(await row(c,r.id),manager,m));}catch(e){fail(res,e);}});
bdtTasksRouter.post('/:id/cancel',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId;try{const input=cancelSchema.parse(req.body),r=await row(c,req.params.id);if(!r)return res.status(404).json({error:'task_not_found'});if(!(await canManage(req,r.department_id)))return res.status(403).json({error:'department_forbidden'});await pool.query(`update public.bdt_tasks set status='cancelled',cancelled_at=now(),cancellation_reason=$3,blocked_reason=null,completed_at=null,updated_at=now() where company_id=$1 and id=$2`,[c,r.id,input.reason]);res.json(shape(await row(c,r.id),true,await actorMember(c,req.auth.userId)));}catch(e){fail(res,e);}});
bdtTasksRouter.post('/:id/reopen',requirePermission('twin','read'),async(req:any,res)=>{const c=req.auth.companyId,r=await row(c,req.params.id);if(!r)return res.status(404).json({error:'task_not_found'});if(!(await canManage(req,r.department_id)))return res.status(403).json({error:'department_forbidden'});if(!['done','cancelled'].includes(r.status))return res.status(409).json({error:'task_not_terminal'});if(!await eligible(c,r.department_id,r.assignee_member_id))return res.status(409).json({error:'ineligible_assignee'});await pool.query(`update public.bdt_tasks set status='todo',completed_at=null,cancelled_at=null,cancellation_reason=null,blocked_reason=null,updated_at=now() where company_id=$1 and id=$2`,[c,r.id]);res.json(shape(await row(c,r.id),true,await actorMember(c,req.auth.userId)));});
